import type { EventCard } from '../../../types';

export const acwEvents: EventCard[] = [
  {
    card_id: 'acw_draft_riots',
    title: 'Draft Riots',
    description: 'Civil unrest over conscription costs you 2 units.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'acw_ironclad',
    title: 'Ironclad Launched',
    description: 'A new warship bolsters your forces. Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'acw_blockade',
    title: 'Naval Blockade',
    description: 'An enemy blockade hurts your economy. Lose production for 2 turns.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'production_bonus', target: 'player', value: -2, duration_turns: 2 },
  },
  {
    card_id: 'acw_foreign_aid',
    title: 'Foreign Aid',
    description: 'European powers send supplies. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'acw_disease_camp',
    title: 'Camp Disease',
    description: 'Disease sweeps through military camps, weakening all sides.',
    category: 'global',
    era_id: 'acw',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'acw_rally',
    title: 'Rally the Troops',
    description: 'Choose: inspire your soldiers or dig in for defense.',
    category: 'player_targeted',
    era_id: 'acw',
    choices: [
      { choice_id: 'attack', label: 'Charge! (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'defense', label: 'Dig in (+1 defense die for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'acw_ironclad_duel',
    title: 'Ironclad Duel',
    description: 'Two iron-plated warships clash in the harbor, cannons thundering across the water. Choose: press the attack with broadsides or reinforce your hull plating and hold the line.',
    category: 'player_targeted',
    era_id: 'acw',
    choices: [
      { choice_id: 'broadside', label: 'Press the attack (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'reinforce', label: 'Reinforce hull (+2 defense die for 1 turn)', effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 1 } },
    ],
  },
  {
    card_id: 'acw_cotton_diplomacy',
    title: 'Cotton Diplomacy',
    description: 'Cotton exports to European mills secure favorable trade terms. British and French merchants line up to buy, and the revenue pours into your war effort.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'acw_guerrilla_raiders',
    title: 'Guerrilla Raiders',
    description: 'Irregular cavalry strikes behind your lines, burning supply depots and cutting telegraph wires. The raids leave your garrisons scrambling to regroup.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'acw_emancipation_decree',
    title: 'Emancipation Decree',
    description: 'A sweeping proclamation of freedom electrifies the population. Thousands of newly liberated men volunteer to take up arms and join the fight.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'acw_railroad_expansion',
    title: 'Railroad Expansion',
    description: 'New rail lines push deeper into contested territory. Choose: rush troops to the front by rail or use the network to supercharge your wartime industry.',
    category: 'player_targeted',
    era_id: 'acw',
    choices: [
      { choice_id: 'troops', label: 'Rush troops by rail (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
      { choice_id: 'industry', label: 'Wartime industry (+2 production for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'acw_typhoid_outbreak',
    title: 'Typhoid Outbreak',
    description: 'Contaminated water supplies spread typhoid through the camps. Soldiers on all sides fall ill by the hundreds, and the fighting grinds to a crawl.',
    category: 'global',
    era_id: 'acw',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'acw_emancipation_fervor',
    title: 'Emancipation Fervor',
    description: 'A bold proclamation inspires your populace. Renewed sense of purpose strengthens resolve and order across your territories.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'acw_draft_riots',
    title: 'Draft Riots',
    description: 'Compulsory conscription sparks violent riots in cities on both sides. Public order collapses as mobs clash with militia.',
    category: 'global',
    era_id: 'acw',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
