import type { EventCard } from '../../../types';

export const acwEvents: EventCard[] = [
  {
    card_id: 'acw_draft_riots',
    title: 'Draft Riots',
    description: 'Civil unrest over conscription costs you 2 units.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'acw_ironclad',
    title: 'Ironclad Launched',
    description: 'A new warship bolsters your forces. Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'acw_blockade',
    title: 'Naval Blockade',
    description: 'An enemy blockade hurts your economy. Lose production for 2 turns.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'production_bonus', target: 'player', value: -2, duration_turns: 2 },
  },
  {
    card_id: 'acw_foreign_aid',
    title: 'Foreign Aid',
    description: 'European powers send supplies. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'acw_disease_camp',
    title: 'Camp Disease',
    description: 'Disease sweeps through military camps, weakening all sides.',
    category: 'global',
    era_id: 'acw',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'acw_rally',
    title: 'Rally the Troops',
    description: 'Choose: inspire your soldiers or dig in for defense.',
    category: 'player_targeted',
    era_id: 'acw',
    choices: [
      { choice_id: 'attack', label: 'Charge! (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'defense', label: 'Dig in (+1 defense die for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'acw_ironclad_duel',
    title: 'Ironclad Duel',
    description: 'Two ironclads circle in the harbor, shells bouncing off iron like hail off a roof. Neither captain will give ground. Choose: open with broadsides, or reinforce the hull and ride it out.',
    category: 'player_targeted',
    era_id: 'acw',
    choices: [
      { choice_id: 'broadside', label: 'Press the attack (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'reinforce', label: 'Reinforce hull (+2 defense die for 1 turn)', effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 1 } },
    ],
  },
  {
    card_id: 'acw_cotton_diplomacy',
    title: 'Cotton Diplomacy',
    description: 'The Liverpool mills are starving for cotton, and your bales fetch a fortune. The gold buys powder and shoes.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'acw_guerrilla_raiders',
    title: 'Guerrilla Raiders',
    description: 'Mosby’s riders hit the supply line at midnight and are gone before the alarm sounds. Two depots in ashes.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'acw_emancipation_decree',
    title: 'Emancipation Decree',
    description: 'Freedmen fill the recruiting offices the week the proclamation is read aloud. New regiments form by the hundred.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'acw_railroad_expansion',
    title: 'Railroad Expansion',
    description: 'The new line reaches the front, and the whole war moves at the speed of a locomotive now. Choose: load the troop cars, or run the factories around the clock.',
    category: 'player_targeted',
    era_id: 'acw',
    choices: [
      { choice_id: 'troops', label: 'Rush troops by rail (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
      { choice_id: 'industry', label: 'Wartime industry (+2 production for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'acw_typhoid_outbreak',
    title: 'Typhoid Outbreak',
    description: 'The creek the whole army drinks from runs foul. Typhoid does what no general managed, and both lines empty into the hospital tents.',
    category: 'global',
    era_id: 'acw',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'acw_emancipation_fervor',
    title: 'Emancipation Fervor',
    description: 'The proclamation gives the war a cause worth bleeding for. The home front steadies.',
    category: 'player_targeted',
    era_id: 'acw',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'acw_draft_riots',
    title: 'Conscription Backlash',
    description: 'The wealthy buy their way out of the draft for three hundred dollars, and the poor riot in the streets over it. Every city locks its doors.',
    category: 'global',
    era_id: 'acw',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
