import type { EventCard } from '../../../types';

export const ancientEvents: EventCard[] = [
  {
    card_id: 'ancient_barbarian_horde',
    title: 'Barbarian Horde',
    description: 'Nomadic raiders sweep across the frontier. Lose 2 units from your largest territories.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'ancient_roman_roads',
    title: 'Roman Roads',
    description: 'New roads accelerate troop movement. Gain 3 reinforcements across your territories.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'ancient_plague',
    title: 'Plague of Antoninus',
    description: 'A devastating plague sweeps the known world, weakening all armies.',
    category: 'global',
    era_id: 'ancient',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'ancient_grain_surplus',
    title: 'Grain Surplus',
    description: 'A bountiful harvest boosts your economy for 2 turns.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'ancient_diplomatic_marriage',
    title: 'Diplomatic Marriage',
    description: 'A royal union forces a temporary truce with a rival.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'ancient_war_elephants',
    title: 'War Elephants',
    description: 'Choose: bolster your attack or strengthen your defense for 2 turns.',
    category: 'player_targeted',
    era_id: 'ancient',
    choices: [
      { choice_id: 'attack', label: 'Attack boost (+1 die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'defense', label: 'Defense boost (+1 die for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'ancient_alexander_ambition',
    title: "Alexander's Ambition",
    description: 'The young conqueror demands the world bend to his will. Channel his ruthless ambition into a devastating assault, or marshal his legendary companions to bolster your ranks.',
    category: 'player_targeted',
    era_id: 'ancient',
    choices: [
      { choice_id: 'attack', label: 'Conquer like Alexander (+2 attack dice for 1 turn)', effect: { type: 'attack_modifier', target: 'player', value: 2, duration_turns: 1 } },
      { choice_id: 'units', label: 'Rally the Companions (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
    ],
  },
  {
    card_id: 'ancient_silk_road_bounty',
    title: 'Silk Road Bounty',
    description: 'Caravans laden with silk, spices, and gold arrive from the East. Trade revenues surge through your empire for 2 turns.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'ancient_slave_revolt',
    title: 'Slave Revolt',
    description: 'Enslaved laborers rise up in a violent rebellion, overwhelming garrisons and seizing weapons. Your empire loses 3 units quelling the uprising.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'ancient_olympic_truce',
    title: 'Olympic Truce',
    description: 'Heralds proclaim the sacred truce of Olympia. You must honor the gods and lay down arms with a rival while the games are held.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'ancient_volcanic_eruption',
    title: 'Vesuvian Eruption',
    description: 'The mountain roars to life, burying cities beneath ash and molten rock. A catastrophic eruption devastates territories across the region.',
    category: 'global',
    era_id: 'ancient',
    effect: { type: 'region_disaster', target: 'region', value: 2 },
    affects_all_players: true,
  },
  {
    card_id: 'ancient_phalanx_reform',
    title: 'Phalanx Reform',
    description: 'Military reformers redesign your battle formations. Choose to adopt the impenetrable shield wall or train additional hoplites for the front lines.',
    category: 'player_targeted',
    era_id: 'ancient',
    choices: [
      { choice_id: 'defense', label: 'Shield wall formation (+2 defense dice for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 2 } },
      { choice_id: 'units', label: 'Train hoplites (+2 units)', effect: { type: 'units_added', target: 'player', value: 2 } },
    ],
  },
  {
    card_id: 'ancient_golden_age',
    title: 'Golden Age of Athens',
    description: 'Art, philosophy, and civic pride flourish across your lands. Citizens rally behind your rule and stability rises.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'ancient_barbarian_migrations',
    title: 'Barbarian Migrations',
    description: 'Massive tribal migrations sweep across the known world, destabilizing borders and disrupting order everywhere.',
    category: 'global',
    era_id: 'ancient',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
