import type { EventCard } from '../../../types';

export const ancientEvents: EventCard[] = [
  {
    card_id: 'ancient_barbarian_horde',
    title: 'Barbarian Horde',
    description: 'Nomadic raiders sweep across the frontier. Lose 2 units from your largest territories.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'ancient_roman_roads',
    title: 'Roman Roads',
    description: 'New roads accelerate troop movement. Gain 3 reinforcements across your territories.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'ancient_plague',
    title: 'Plague of Antoninus',
    description: 'Fever empties the camps from Rome to the Tigris. Every army loses men to the sickness.',
    category: 'global',
    era_id: 'ancient',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'ancient_grain_surplus',
    title: 'Grain Surplus',
    description: 'A bountiful harvest boosts your economy for 2 turns.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'ancient_diplomatic_marriage',
    title: 'Diplomatic Marriage',
    description: 'A royal union forces a temporary truce with a rival.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'ancient_war_elephants',
    title: 'War Elephants',
    description: 'Choose: bolster your attack or strengthen your defense for 2 turns.',
    category: 'player_targeted',
    era_id: 'ancient',
    choices: [
      { choice_id: 'attack', label: 'Attack boost (+1 die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'defense', label: 'Defense boost (+1 die for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'ancient_alexander_ambition',
    title: "Alexander's Ambition",
    description: 'Alexander wants the whole map and he wants it now. Spend that hunger on the offensive, or call up his Companion cavalry to fill out your ranks.',
    category: 'player_targeted',
    era_id: 'ancient',
    choices: [
      { choice_id: 'attack', label: 'Conquer like Alexander (+2 attack dice for 1 turn)', effect: { type: 'attack_modifier', target: 'player', value: 2, duration_turns: 1 } },
      { choice_id: 'units', label: 'Rally the Companions (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
    ],
  },
  {
    card_id: 'ancient_silk_road_bounty',
    title: 'Silk Road Bounty',
    description: 'The Samarkand caravans get through. Your treasury runs fat for 2 turns.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'ancient_slave_revolt',
    title: 'Slave Revolt',
    description: 'The mines and latifundia rise against you, and they have your own spears. Putting it down costs 3 units.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'ancient_olympic_truce',
    title: 'Olympic Truce',
    description: 'The heralds declare the sacred truce of Olympia. Snub the gods over a foot-race and you look like a tyrant, so you stand down with a rival until the games are done.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'ancient_volcanic_eruption',
    title: 'Vesuvian Eruption',
    description: 'Vesuvius takes Pompeii and Herculaneum in an afternoon. The ash falls for days and guts every territory in reach.',
    category: 'global',
    era_id: 'ancient',
    effect: { type: 'region_disaster', target: 'region', value: 2 },
    affects_all_players: true,
  },
  {
    card_id: 'ancient_phalanx_reform',
    title: 'Phalanx Reform',
    description: 'Your drillmasters want to rebuild the phalanx. Lock the shields into a wall, or just put more hoplites in the line.',
    category: 'player_targeted',
    era_id: 'ancient',
    choices: [
      { choice_id: 'defense', label: 'Shield wall formation (+2 defense dice for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 2 } },
      { choice_id: 'units', label: 'Train hoplites (+2 units)', effect: { type: 'units_added', target: 'player', value: 2 } },
    ],
  },
  {
    card_id: 'ancient_golden_age',
    title: 'Golden Age of Athens',
    description: 'The Parthenon goes up and the agora hums with new ideas. Pride in your rule runs high and stability rises.',
    category: 'player_targeted',
    era_id: 'ancient',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'ancient_barbarian_migrations',
    title: 'Barbarian Migrations',
    description: 'Whole peoples are on the move, Goths ahead of the Huns, pressing every frontier at once. No realm holds its order and stability drops for all.',
    category: 'global',
    era_id: 'ancient',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
