import type { EventCard } from '../../../types';

export const coldwarEvents: EventCard[] = [
  {
    card_id: 'coldwar_proxy_war',
    title: 'Proxy War',
    description: 'A regional proxy conflict erupts. Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'coldwar_arms_race',
    title: 'Arms Race',
    description: 'Massive military buildup grants +1 attack die for 2 turns.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_detente',
    title: 'Détente',
    description: 'A thaw in relations forces a truce with a rival for 2 turns.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'coldwar_space_race',
    title: 'Space Race Victory',
    description: 'Your space program inspires the nation. Production bonus for 2 turns.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_nuclear_scare',
    title: 'Nuclear Scare',
    description: 'Fear of nuclear war weakens all armies globally.',
    category: 'global',
    era_id: 'coldwar',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'coldwar_espionage',
    title: 'Espionage Operation',
    description: 'Choose: sabotage enemy forces or steal military secrets.',
    category: 'player_targeted',
    era_id: 'coldwar',
    choices: [
      { choice_id: 'sabotage', label: 'Sabotage (enemy loses 2 units)', effect: { type: 'enemy_units_removed', target: 'player', value: 2 } },
      { choice_id: 'secrets', label: 'Military secrets (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'coldwar_proxy_conflict',
    title: 'Proxy Conflict Escalation',
    description: 'A simmering border dispute between client states threatens to drag the superpowers in. Choose: commit advisors to the front lines or rush in fresh conscripts to hold the perimeter.',
    category: 'player_targeted',
    era_id: 'coldwar',
    choices: [
      { choice_id: 'advisors', label: 'Deploy military advisors (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'conscripts', label: 'Rush in reinforcements (+3 units)', effect: { type: 'units_added', target: 'player', value: 3 } },
    ],
  },
  {
    card_id: 'coldwar_economic_sanctions',
    title: 'Economic Sanctions',
    description: 'The international community imposes crippling trade sanctions on your regime. Factories stall and supply chains collapse under the embargo.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'production_bonus', target: 'player', value: -2, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_space_achievement',
    title: 'Space Achievement',
    description: 'Your nation lands a historic space mission, capturing the world\'s imagination. The surge of national pride fuels industrial output across every sector.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_berlin_crisis',
    title: 'Berlin Crisis',
    description: 'Tensions flare at the divided city as tanks face off across the checkpoint. Your forces dig in behind concrete barriers, fortifying every position.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 1 },
  },
  {
    card_id: 'coldwar_arms_buildup',
    title: 'Arms Buildup',
    description: 'Intelligence reports a widening missile gap. Congress authorizes an emergency military expansion, flooding your bases with fresh troops and materiel.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'coldwar_cuban_standoff',
    title: 'Cuban Standoff',
    description: 'Reconnaissance photos reveal offensive weapons on a nearby island. The world holds its breath. Choose: escalate with a show of force or negotiate a stand-down.',
    category: 'player_targeted',
    era_id: 'coldwar',
    choices: [
      { choice_id: 'escalate', label: 'Show of force (+2 attack die for 1 turn)', effect: { type: 'attack_modifier', target: 'player', value: 2, duration_turns: 1 } },
      { choice_id: 'negotiate', label: 'Negotiate a stand-down (truce for 2 turns)', effect: { type: 'truce', target: 'player', value: 2 } },
    ],
  },
];
