import type { EventCard } from '../../../types';

export const coldwarEvents: EventCard[] = [
  {
    card_id: 'coldwar_proxy_war',
    title: 'Proxy War',
    description: 'A regional proxy conflict erupts. Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'coldwar_arms_race',
    title: 'Arms Race',
    description: 'Massive military buildup grants +1 attack die for 2 turns.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_detente',
    title: 'Détente',
    description: 'A thaw in relations forces a truce with a rival for 2 turns.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'coldwar_space_race',
    title: 'Space Race Victory',
    description: 'Your space program inspires the nation. Production bonus for 2 turns.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_nuclear_scare',
    title: 'Nuclear Scare',
    description: 'Fear of nuclear war weakens all armies globally.',
    category: 'global',
    era_id: 'coldwar',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'coldwar_espionage',
    title: 'Espionage Operation',
    description: 'Choose: sabotage enemy forces or steal military secrets.',
    category: 'player_targeted',
    era_id: 'coldwar',
    choices: [
      { choice_id: 'sabotage', label: 'Sabotage (enemy loses 2 units)', effect: { type: 'enemy_units_removed', target: 'player', value: 2 } },
      { choice_id: 'secrets', label: 'Military secrets (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'coldwar_proxy_conflict',
    title: 'Proxy Conflict Escalation',
    description: 'Two client states are shooting at each other again, and your name is on the invoices. Choose: send advisors, or send bodies.',
    category: 'player_targeted',
    era_id: 'coldwar',
    choices: [
      { choice_id: 'advisors', label: 'Deploy military advisors (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'conscripts', label: 'Rush in reinforcements (+3 units)', effect: { type: 'units_added', target: 'player', value: 3 } },
    ],
  },
  {
    card_id: 'coldwar_economic_sanctions',
    title: 'Economic Sanctions',
    description: 'An embargo cuts you off from the imports your factories run on. Production stalls for 2 turns.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'production_bonus', target: 'player', value: -2, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_space_achievement',
    title: 'Space Achievement',
    description: 'Your flag is on the Moon and the newsreels won’t stop running it. Every factory wants in on the moment.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'coldwar_berlin_crisis',
    title: 'Berlin Crisis',
    description: 'Tanks idle muzzle-to-muzzle at Checkpoint Charlie. Nobody blinks, and your men pour concrete.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 1 },
  },
  {
    card_id: 'coldwar_arms_buildup',
    title: 'Arms Buildup',
    description: 'The “missile gap” is mostly a budget request, but it works: 4 fresh divisions report for duty.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'coldwar_cuban_standoff',
    title: 'Cuban Standoff',
    description: 'U-2 photos put enemy missiles ninety miles off your coast. Thirteen days to decide. Choose: a show of force, or a quiet trade for the stand-down.',
    category: 'player_targeted',
    era_id: 'coldwar',
    choices: [
      { choice_id: 'escalate', label: 'Show of force (+2 attack die for 1 turn)', effect: { type: 'attack_modifier', target: 'player', value: 2, duration_turns: 1 } },
      { choice_id: 'negotiate', label: 'Negotiate a stand-down (truce for 2 turns)', effect: { type: 'truce', target: 'player', value: 2 } },
    ],
  },
  {
    card_id: 'coldwar_space_race_triumph',
    title: 'Space Race Triumph',
    description: 'A ticker-tape parade for the cosmonauts, and for one shining week nobody questions the government.',
    category: 'player_targeted',
    era_id: 'coldwar',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'coldwar_nuclear_anxiety',
    title: 'Nuclear Anxiety',
    description: 'A near-miss nuclear incident sparks worldwide panic. Civil unrest and fear of annihilation destabilize every regime.',
    category: 'global',
    era_id: 'coldwar',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
