import type { EventCard } from '../../../types';

export const discoveryEvents: EventCard[] = [
  {
    card_id: 'discovery_new_world',
    title: 'New World Riches',
    description: 'Treasure fleets bring wealth. Production bonus for 2 turns.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'discovery_piracy',
    title: 'Golden Age of Piracy',
    description: 'Pirates raid your coasts, costing 2 units.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'discovery_colonial_troops',
    title: 'Colonial Reinforcements',
    description: 'Troops arrive from the colonies. Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'discovery_smallpox',
    title: 'Smallpox Outbreak',
    description: 'Disease ravages populations worldwide.',
    category: 'global',
    era_id: 'discovery',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'discovery_trade_winds',
    title: 'Favorable Trade Winds',
    description: 'Choose: boost naval power or strengthen land armies.',
    category: 'player_targeted',
    era_id: 'discovery',
    choices: [
      { choice_id: 'attack', label: 'Naval superiority (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'units', label: 'Land reinforcements (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
    ],
  },
  {
    card_id: 'discovery_circumnavigation',
    title: 'Circumnavigation',
    description: 'Your expedition completes a voyage around the globe, opening new horizons. Recruit seasoned sailors to your cause, or establish profitable trade posts along the route.',
    category: 'player_targeted',
    era_id: 'discovery',
    choices: [
      { choice_id: 'units', label: 'Recruit veteran sailors (+3 units)', effect: { type: 'units_added', target: 'player', value: 3 } },
      { choice_id: 'production', label: 'Establish trade posts (+2 production for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'discovery_religious_mission',
    title: 'Religious Mission',
    description: 'Missionaries spread the faith to distant lands, forging bonds of peace with neighboring powers. A truce is declared in the name of God.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'truce', target: 'player', value: 3 },
  },
  {
    card_id: 'discovery_hurricane_season',
    title: 'Hurricane Season',
    description: 'Monstrous storms batter coastlines and sink fleets. No empire is spared as the hurricane season unleashes its fury across the region.',
    category: 'global',
    era_id: 'discovery',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'discovery_mercantilism',
    title: 'Rise of Mercantilism',
    description: 'Your ministers adopt mercantilist policies, hoarding gold and imposing tariffs on rivals. Treasury revenues increase for 2 turns.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'discovery_mutiny',
    title: 'Crew Mutiny',
    description: 'Months at sea with dwindling rations push your crews to the breaking point. Sailors mutiny, seizing ships and abandoning their posts. You lose 3 units.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'discovery_treaty_tordesillas',
    title: 'Treaty of Tordesillas',
    description: 'A papal decree divides the new world between rival powers. The treaty strengthens your defensive claims over colonial holdings for 3 turns.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 },
  },
  {
    card_id: 'discovery_spice_trade',
    title: 'Spice Trade Windfall',
    description: 'Your merchants secure exclusive access to the lucrative spice islands. Flood your markets with exotic goods, or hire mercenaries with the windfall profits.',
    category: 'player_targeted',
    era_id: 'discovery',
    choices: [
      { choice_id: 'production', label: 'Spice monopoly (+3 production for 1 turn)', effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 1 } },
      { choice_id: 'units', label: 'Hire mercenaries (+2 units)', effect: { type: 'units_added', target: 'player', value: 2 } },
    ],
  },
  {
    card_id: 'discovery_colonial_prosperity',
    title: 'Colonial Prosperity',
    description: 'Wealth from the New World pours into your coffers, funding civic improvements and bolstering loyalty across your territories.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'discovery_reformation_turmoil',
    title: 'Reformation Turmoil',
    description: 'Religious upheaval tears through every nation. Riots and iconoclasm destabilize governments across the continent.',
    category: 'global',
    era_id: 'discovery',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
