import type { EventCard } from '../../../types';

export const discoveryEvents: EventCard[] = [
  {
    card_id: 'discovery_new_world',
    title: 'New World Riches',
    description: 'Treasure fleets bring wealth. Production bonus for 2 turns.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'discovery_piracy',
    title: 'Golden Age of Piracy',
    description: 'Pirates raid your coasts, costing 2 units.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'discovery_colonial_troops',
    title: 'Colonial Reinforcements',
    description: 'Troops arrive from the colonies. Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'discovery_smallpox',
    title: 'Smallpox Outbreak',
    description: 'Disease ravages populations worldwide.',
    category: 'global',
    era_id: 'discovery',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'discovery_trade_winds',
    title: 'Favorable Trade Winds',
    description: 'Choose: boost naval power or strengthen land armies.',
    category: 'player_targeted',
    era_id: 'discovery',
    choices: [
      { choice_id: 'attack', label: 'Naval superiority (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'units', label: 'Land reinforcements (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
    ],
  },
  {
    card_id: 'discovery_circumnavigation',
    title: 'Circumnavigation',
    description: 'Three ships left. One came home, hull crusted with salt and rumor. Sign on its survivors, or bank the maps as trade posts.',
    category: 'player_targeted',
    era_id: 'discovery',
    choices: [
      { choice_id: 'units', label: 'Recruit veteran sailors (+3 units)', effect: { type: 'units_added', target: 'player', value: 3 } },
      { choice_id: 'production', label: 'Establish trade posts (+2 production for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'discovery_religious_mission',
    title: 'Religious Mission',
    description: 'Your missionaries broker a peace nobody dares break under the cross. Truce holds for 3 turns.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'truce', target: 'player', value: 3 },
  },
  {
    card_id: 'discovery_hurricane_season',
    title: 'Hurricane Season',
    description: 'The Caribbean turns black and every coast pays. No fleet rides this one out.',
    category: 'global',
    era_id: 'discovery',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'discovery_mercantilism',
    title: 'Rise of Mercantilism',
    description: 'Tariff the neighbors, hoard the bullion, call it patriotism. Revenue climbs for 2 turns.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
  },
  {
    card_id: 'discovery_mutiny',
    title: 'Crew Mutiny',
    description: 'The biscuit ran to weevils a month ago. The crew takes the ship and leaves you the longboat. Lose 3 units.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'discovery_treaty_tordesillas',
    title: 'Treaty of Tordesillas',
    description: 'A line drawn on a map in Rome makes your colonial claims defensible for 3 turns.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 },
  },
  {
    card_id: 'discovery_spice_trade',
    title: 'Spice Trade Windfall',
    description: 'You hold the only deck loading nutmeg out of the Banda Islands. Corner the market, or spend the profits on hired swords.',
    category: 'player_targeted',
    era_id: 'discovery',
    choices: [
      { choice_id: 'production', label: 'Spice monopoly (+3 production for 1 turn)', effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 1 } },
      { choice_id: 'units', label: 'Hire mercenaries (+2 units)', effect: { type: 'units_added', target: 'player', value: 2 } },
    ],
  },
  {
    card_id: 'discovery_colonial_prosperity',
    title: 'Colonial Prosperity',
    description: 'Silver from Potosí buys roads, bread, and quiet. Loyalty rises.',
    category: 'player_targeted',
    era_id: 'discovery',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'discovery_reformation_turmoil',
    title: 'Reformation Turmoil',
    description: 'Theses get nailed to doors, altars get smashed. No throne sits easy this season.',
    category: 'global',
    era_id: 'discovery',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
