import type { EventCard } from '../../../types';

export const galaxyageEvents: EventCard[] = [
  {
    card_id: 'ga_lane_closure',
    title: 'Lane Closure',
    description: 'Gravitic shear forces ships onto longer burns — lose 2 units.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'ga_alliance_summit',
    title: 'Alliance Summit',
    description: 'Diplomatic cables reopen — declare a short truce with a rival.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'ga_resource_surge',
    title: 'Resource Surge',
    description: 'Convoys arrive ahead of schedule — extra production this cycle.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 3 },
  },
  {
    card_id: 'ga_sensor_blackout',
    title: 'Sensor Blackout',
    description: 'Jamming floods local space — lose 1 attack die this turn.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'attack_modifier', target: 'player', value: -1, duration_turns: 1 },
  },
  {
    card_id: 'ga_nebula_storm',
    title: 'Nebula Storm',
    description: 'Ion clouds disrupt fleets everywhere.',
    category: 'global',
    era_id: 'galaxy_age',
    affects_all_players: true,
    effect: { type: 'region_disaster', target: 'region', value: 1 },
  },
  {
    card_id: 'ga_colony_grant',
    title: 'Colony Grant',
    description: 'A charter awards settlement rights — gain 2 units on your strongest territory.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'units_added', target: 'player', value: 2 },
  },
  {
    card_id: 'ga_charted_vault',
    title: 'Charted Vault',
    description: 'Salvage crews crack a derelict archive ship — bank a windfall of tech points.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'tech_bonus', target: 'player', value: 5 },
  },
  {
    card_id: 'ga_refugee_fleet',
    title: 'Refugee Fleet',
    description: 'Displaced civilians enlist for safety — gain 3 units on a chosen territory.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'ga_black_hole_drift',
    title: 'Black Hole Drift',
    description: 'A wandering singularity drains every fleet — galaxy-wide casualties.',
    category: 'global',
    era_id: 'galaxy_age',
    affects_all_players: true,
    effect: { type: 'region_disaster', target: 'region', value: 2 },
  },
  {
    card_id: 'ga_lane_surge',
    title: 'Lane Surge',
    description: 'A short-lived lane optimum boosts production this cycle.',
    category: 'player_targeted',
    era_id: 'galaxy_age',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
];
