import type { EventCard } from '../../../types';

export const medievalEvents: EventCard[] = [
  {
    card_id: 'medieval_crusade',
    title: 'Crusade Called',
    description: 'Religious fervor grants +1 attack die for 2 turns.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'medieval_black_death',
    title: 'The Black Death',
    description: 'Plague devastates all lands, removing 1 unit from every territory.',
    category: 'global',
    era_id: 'medieval',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'medieval_feudal_levy',
    title: 'Feudal Levy',
    description: 'Your vassals answer the call. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'medieval_harvest_festival',
    title: 'Harvest Festival',
    description: 'A great harvest boosts production for 2 turns.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'medieval_peasant_revolt',
    title: 'Peasant Revolt',
    description: 'Unrest costs you 3 units from your empire.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'medieval_castle_upgrade',
    title: 'Castle Fortifications',
    description: 'Choose: reinforce your defenses or train siege engineers.',
    category: 'player_targeted',
    era_id: 'medieval',
    choices: [
      { choice_id: 'defense', label: 'Fortify (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'attack', label: 'Siege engineers (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'medieval_trade_fair',
    title: 'Grand Trade Fair',
    description: 'Merchants from across Christendom converge on your lands for a great fair. The bustling commerce fills your coffers for 1 turn.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'production_bonus', target: 'player', value: 4, duration_turns: 1 },
  },
  {
    card_id: 'medieval_feudal_conscription',
    title: 'Feudal Conscription',
    description: 'Your lords invoke their feudal obligation, mustering peasants and men-at-arms from every hamlet and manor. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'medieval_heresy_spreads',
    title: 'Heresy Spreads',
    description: 'A dangerous heretical movement fractures your realm. Soldiers desert their posts and monks abandon their duties, costing you 2 units.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'medieval_mongol_envoy',
    title: 'Mongol Envoy',
    description: 'A Mongol emissary arrives bearing gifts and threats in equal measure. Adopt their fearsome cavalry tactics, or secure lucrative access to their vast trade network.',
    category: 'player_targeted',
    era_id: 'medieval',
    choices: [
      { choice_id: 'attack', label: 'Mongol cavalry tactics (+1 attack die for 3 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'production', label: 'Trade network access (+2 production for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'medieval_famine',
    title: 'Great Famine',
    description: 'Torrential rains rot the crops in every field. Starvation grips the land and armies weaken as rations dwindle to nothing.',
    category: 'global',
    era_id: 'medieval',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'medieval_siege_warfare',
    title: 'Siege Warfare Advances',
    description: 'Engineers develop new techniques for both building and breaking fortifications. Choose to master the art of the siege or perfect your castle defenses.',
    category: 'player_targeted',
    era_id: 'medieval',
    choices: [
      { choice_id: 'defense', label: 'Improved fortifications (+2 defense dice for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 2 } },
      { choice_id: 'attack', label: 'Siege mastery (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'medieval_royal_charter',
    title: 'Royal Charter Granted',
    description: 'The crown issues a charter guaranteeing rights and privileges to your towns. Morale and order improve across your realm.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'medieval_great_famine',
    title: 'The Great Famine',
    description: 'Failed harvests and endless rain bring widespread starvation. Peasant revolts and despair grip every kingdom.',
    category: 'global',
    era_id: 'medieval',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
