import type { EventCard } from '../../../types';

export const medievalEvents: EventCard[] = [
  {
    card_id: 'medieval_crusade',
    title: 'Crusade Called',
    description: 'Religious fervor grants +1 attack die for 2 turns.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'medieval_black_death',
    title: 'The Black Death',
    description: 'Plague devastates all lands, removing 1 unit from every territory.',
    category: 'global',
    era_id: 'medieval',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'medieval_feudal_levy',
    title: 'Feudal Levy',
    description: 'Your vassals answer the call. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'medieval_harvest_festival',
    title: 'Harvest Festival',
    description: 'A great harvest boosts production for 2 turns.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'medieval_peasant_revolt',
    title: 'Peasant Revolt',
    description: 'Unrest costs you 3 units from your empire.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'medieval_castle_upgrade',
    title: 'Castle Fortifications',
    description: 'Choose: reinforce your defenses or train siege engineers.',
    category: 'player_targeted',
    era_id: 'medieval',
    choices: [
      { choice_id: 'defense', label: 'Fortify (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'attack', label: 'Siege engineers (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'medieval_trade_fair',
    title: 'Grand Trade Fair',
    description: 'The Champagne fairs come to your roads. Coffers overflow for one turn, then the wagons roll on.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'production_bonus', target: 'player', value: 4, duration_turns: 1 },
  },
  {
    card_id: 'medieval_feudal_conscription',
    title: 'Feudal Conscription',
    description: 'Forty days’ service owed, forty days’ service taken. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'medieval_heresy_spreads',
    title: 'Heresy Spreads',
    description: 'The Cathars preach in your villages and the faith curdles. Two units melt away to follow them.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'medieval_mongol_envoy',
    title: 'Mongol Envoy',
    description: 'A rider from the Golden Horde waits at your gate. Learn how the steppe fights, or buy a place on the road to Karakorum.',
    category: 'player_targeted',
    era_id: 'medieval',
    choices: [
      { choice_id: 'attack', label: 'Mongol cavalry tactics (+1 attack die for 3 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'production', label: 'Trade network access (+2 production for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'medieval_famine',
    title: 'Great Famine',
    description: 'The rains do not stop and the grain rots standing. Every territory loses a unit to hunger.',
    category: 'global',
    era_id: 'medieval',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'medieval_siege_warfare',
    title: 'Siege Warfare Advances',
    description: 'The trebuchet changes every reckoning of stone and wall. Build them, or build against them.',
    category: 'player_targeted',
    era_id: 'medieval',
    choices: [
      { choice_id: 'defense', label: 'Improved fortifications (+2 defense dice for 2 turns)', effect: { type: 'defense_modifier', target: 'player', value: 2, duration_turns: 2 } },
      { choice_id: 'attack', label: 'Siege mastery (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'medieval_royal_charter',
    title: 'Royal Charter Granted',
    description: 'A sealed charter buys your towns their liberties. Cheaper than putting down the next revolt, and your realm settles.',
    category: 'player_targeted',
    era_id: 'medieval',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'medieval_great_famine',
    title: 'The Great Famine',
    description: 'Three winters of failed harvest. The chroniclers stop counting the dead, and order frays in every kingdom.',
    category: 'global',
    era_id: 'medieval',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
