import type { EventCard } from '../../../types';

export const modernEvents: EventCard[] = [
  {
    card_id: 'modern_cyber_attack',
    title: 'Cyber Attack',
    description: 'A cyberattack disrupts your military operations. Lose 2 units.',
    category: 'player_targeted',
    era_id: 'modern',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'modern_drone_strike',
    title: 'Drone Strike Program',
    description: 'Precision strikes grant +1 attack die for 2 turns.',
    category: 'player_targeted',
    era_id: 'modern',
    effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'modern_economic_boom',
    title: 'Economic Boom',
    description: 'A booming economy boosts production for 3 turns.',
    category: 'player_targeted',
    era_id: 'modern',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 3 },
  },
  {
    card_id: 'modern_un_resolution',
    title: 'UN Resolution',
    description: 'The United Nations imposes a ceasefire with a rival.',
    category: 'player_targeted',
    era_id: 'modern',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'modern_pandemic',
    title: 'Global Pandemic',
    description: 'A pandemic weakens militaries worldwide.',
    category: 'global',
    era_id: 'modern',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'modern_military_aid',
    title: 'International Military Aid',
    description: 'Choose: accept troops or advanced weapons.',
    category: 'player_targeted',
    era_id: 'modern',
    choices: [
      { choice_id: 'troops', label: 'Troop deployment (+5 units)', effect: { type: 'units_added', target: 'player', value: 5 } },
      { choice_id: 'weapons', label: 'Advanced weapons (+1 attack die for 3 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'modern_drone_warfare',
    title: 'Drone Warfare',
    description: 'Your military deploys next-generation autonomous combat drones. Their precision targeting gives your forces a decisive edge on the battlefield.',
    category: 'player_targeted',
    era_id: 'modern',
    effect: { type: 'attack_modifier', target: 'player', value: 2, duration_turns: 1 },
  },
  {
    card_id: 'modern_trade_agreement',
    title: 'International Trade Agreement',
    description: 'A landmark multilateral trade deal is on the table. Choose: open your markets to boost the economy or secure a mutual defense pact with trade partners.',
    category: 'player_targeted',
    era_id: 'modern',
    choices: [
      { choice_id: 'markets', label: 'Open markets (+3 production for 2 turns)', effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 } },
      { choice_id: 'defense_pact', label: 'Defense pact (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'modern_refugee_crisis',
    title: 'Refugee Crisis',
    description: 'Waves of displaced civilians overwhelm border regions. Military resources are diverted to manage the humanitarian catastrophe, weakening your front lines.',
    category: 'player_targeted',
    era_id: 'modern',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'modern_un_peacekeeping',
    title: 'UN Peacekeeping Mission',
    description: 'The Security Council authorizes blue helmets to patrol the contested zone. You are compelled to observe a temporary cessation of hostilities with a rival.',
    category: 'player_targeted',
    era_id: 'modern',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'modern_pandemic_wave',
    title: 'Pandemic Wave',
    description: 'A virulent new strain sweeps across borders unchecked. Quarantines cripple logistics and troop movements on every front as hospitals overflow.',
    category: 'global',
    era_id: 'modern',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'modern_tech_breakthrough',
    title: 'Tech Breakthrough',
    description: 'Your research labs achieve a major technological breakthrough. Choose: rapidly scale production with new automation or deploy cutting-edge weapons systems.',
    category: 'player_targeted',
    era_id: 'modern',
    choices: [
      { choice_id: 'automation', label: 'Automate production (+4 production for 1 turn)', effect: { type: 'production_bonus', target: 'player', value: 4, duration_turns: 1 } },
      { choice_id: 'weapons', label: 'Deploy weapons (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
];
