import type { EventCard } from '../../../types';

export const risorgimentoEvents: EventCard[] = [
  {
    card_id: 'risorgimento_revolution',
    title: 'Popular Revolution',
    description: 'Revolutionary fervor spreads! Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'risorgimento_foreign_intervention',
    title: 'Foreign Intervention',
    description: 'A great power intervenes. Lose 2 units to their forces.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'risorgimento_garibaldi',
    title: 'Garibaldi\'s Expedition',
    description: 'Volunteer fighters rally to your cause. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'risorgimento_cholera',
    title: 'Cholera Outbreak',
    description: 'Disease weakens armies across the peninsula.',
    category: 'global',
    era_id: 'risorgimento',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'risorgimento_congress',
    title: 'Congress of Nations',
    description: 'Diplomatic pressure forces a temporary ceasefire.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'risorgimento_secret_society',
    title: 'Secret Society',
    description: 'Choose: undermine enemy defenses or strengthen your networks.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    choices: [
      { choice_id: 'attack', label: 'Undermine (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'production', label: 'Networks (production bonus for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'riso_garibaldi_rallies',
    title: 'Garibaldi Rallies the South',
    description: 'Garibaldi steps ashore at Marsala with a thousand Redshirts. Sicilian peasants are already walking off the fields to join him. Choose: march the column north, or drill it for the fights ahead.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    choices: [
      { choice_id: 'march', label: 'March north (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
      { choice_id: 'spirit', label: 'Fighting spirit (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'riso_papal_intervention',
    title: 'Papal Intervention',
    description: 'Pius IX sends down an encyclical, and the Catholic powers lean on everyone with an army in the field. The guns go quiet for two turns. Nobody is happy about it.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'riso_cholera_epidemic',
    title: 'Cholera Epidemic',
    description: 'Cholera comes up out of the wells and into every barracks on the peninsula. It does not read uniforms.',
    category: 'global',
    era_id: 'risorgimento',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'riso_austrian_crackdown',
    title: 'Austrian Crackdown',
    description: 'The Austrian garrison goes door to door through the quarter. Three of your companies are marched off in chains to a Habsburg fortress.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'riso_piedmont_diplomacy',
    title: 'Piedmontese Diplomacy',
    description: 'Cavour has been working the European courts on Piedmont’s behalf, and one of them is finally ready to deal. Choose: a defensive pact, or their money.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    choices: [
      { choice_id: 'alliance', label: 'Defensive alliance (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'investment', label: 'Foreign investment (+2 production for 2 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'riso_secret_societies',
    title: 'Secret Societies Mobilize',
    description: 'The Carbonari and Giovine Italia activate their clandestine networks across the peninsula. Arms caches are opened and smuggled funds flow into your treasury.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'riso_national_awakening',
    title: 'National Awakening',
    description: 'Patriotic literature and revolutionary ideals inspire your people. A wave of civic pride stabilizes your territories.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'riso_reactionary_crackdown',
    title: 'Reactionary Crackdown',
    description: 'Conservative powers suppress liberal movements across Europe. Police raids and censorship destabilize every state.',
    category: 'global',
    era_id: 'risorgimento',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
