import type { EventCard } from '../../../types';

export const risorgimentoEvents: EventCard[] = [
  {
    card_id: 'risorgimento_revolution',
    title: 'Popular Revolution',
    description: 'Revolutionary fervor spreads! Gain 3 reinforcements.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_added', target: 'player', value: 3 },
  },
  {
    card_id: 'risorgimento_foreign_intervention',
    title: 'Foreign Intervention',
    description: 'A great power intervenes. Lose 2 units to their forces.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'risorgimento_garibaldi',
    title: 'Garibaldi\'s Expedition',
    description: 'Volunteer fighters rally to your cause. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'risorgimento_cholera',
    title: 'Cholera Outbreak',
    description: 'Disease weakens armies across the peninsula.',
    category: 'global',
    era_id: 'risorgimento',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'risorgimento_congress',
    title: 'Congress of Nations',
    description: 'Diplomatic pressure forces a temporary ceasefire.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'risorgimento_secret_society',
    title: 'Secret Society',
    description: 'Choose: undermine enemy defenses or strengthen your networks.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    choices: [
      { choice_id: 'attack', label: 'Undermine (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
      { choice_id: 'production', label: 'Networks (production bonus for 3 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'riso_garibaldi_rallies',
    title: 'Garibaldi Rallies the South',
    description: 'The legendary general lands in the Mezzogiorno, and peasants flock to his red-shirted ranks. Choose: march north with a swelling army or sharpen their fighting spirit for the battles ahead.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    choices: [
      { choice_id: 'march', label: 'March north (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
      { choice_id: 'spirit', label: 'Fighting spirit (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'riso_papal_intervention',
    title: 'Papal Intervention',
    description: 'The Pope issues a stern encyclical condemning further bloodshed on the Italian peninsula. Under pressure from Catholic nations, all belligerents agree to a temporary ceasefire.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'riso_cholera_epidemic',
    title: 'Cholera Epidemic',
    description: 'Filthy water and overcrowded barracks unleash a devastating cholera outbreak. The disease respects no flags, ravaging encampments on every side of the conflict.',
    category: 'global',
    era_id: 'risorgimento',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'riso_austrian_crackdown',
    title: 'Austrian Crackdown',
    description: 'Habsburg authorities launch a brutal sweep of suspected nationalists. Mass arrests and forced conscription into imperial labor battalions decimate your ranks.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'riso_piedmont_diplomacy',
    title: 'Piedmontese Diplomacy',
    description: 'Cavour\'s masterful negotiations with European courts bear fruit. Choose: secure a defensive alliance or attract foreign investment to fuel the war machine.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    choices: [
      { choice_id: 'alliance', label: 'Defensive alliance (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'investment', label: 'Foreign investment (+2 production for 2 turns)', effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'riso_secret_societies',
    title: 'Secret Societies Mobilize',
    description: 'The Carbonari and Giovine Italia activate their clandestine networks across the peninsula. Arms caches are opened and smuggled funds flow into your treasury.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 2 },
  },
  {
    card_id: 'riso_national_awakening',
    title: 'National Awakening',
    description: 'Patriotic literature and revolutionary ideals inspire your people. A wave of civic pride stabilizes your territories.',
    category: 'player_targeted',
    era_id: 'risorgimento',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'riso_reactionary_crackdown',
    title: 'Reactionary Crackdown',
    description: 'Conservative powers suppress liberal movements across Europe. Police raids and censorship destabilize every state.',
    category: 'global',
    era_id: 'risorgimento',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
