import type { EventCard } from '../../../types';

export const spaceageEvents: EventCard[] = [
  {
    card_id: 'sa_solar_flare',
    title: 'Solar Flare',
    description: 'A massive coronal mass ejection disrupts orbital infrastructure and surface electronics. Power grids across your territories buckle.',
    category: 'global',
    era_id: 'space_age',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'sa_asteroid_mining',
    title: 'Asteroid Mining Strike',
    description: 'Prospector drones strike a rare-metals motherlode. Tech bonanza for everyone riding the supply chain.',
    category: 'player_targeted',
    era_id: 'space_age',
    effect: { type: 'production_bonus', target: 'player', value: 4, duration_turns: 2 },
  },
  {
    card_id: 'sa_orbital_bombardment',
    title: 'Orbital Bombardment',
    description: 'A kinetic rod from a rival\'s space platform punches through the atmosphere and obliterates a staging area. Lose 2 units.',
    category: 'player_targeted',
    era_id: 'space_age',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'sa_first_contact',
    title: 'First Contact Signal',
    description: 'Radio telescopes detect a non-terrestrial signal of unknown origin. Global research budgets spike overnight.',
    category: 'global',
    era_id: 'space_age',
    effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 },
    affects_all_players: true,
  },
  {
    card_id: 'sa_climate_collapse',
    title: 'Climate Tipping Point',
    description: 'A long-feared feedback loop triggers — glacial melt, monsoon failure, and flooded coastal megacities follow within weeks.',
    category: 'global',
    era_id: 'space_age',
    effect: { type: 'stability_change', target: 'player', value: -15 },
    affects_all_players: true,
  },
  {
    card_id: 'sa_cyber_pandemic',
    title: 'Cyber Pandemic',
    description: 'A self-mutating worm infects every tech-gen grid in the network. Research output crashes worldwide.',
    category: 'global',
    era_id: 'space_age',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'sa_lunar_quake',
    title: 'Lunar Quake',
    description: 'A subsurface moonquake cracks habitat domes. Emergency protocols divert supply shipments from Earth.',
    category: 'player_targeted',
    era_id: 'space_age',
    effect: { type: 'units_removed', target: 'player', value: 1 },
  },
  {
    card_id: 'sa_megacity_riots',
    title: 'Megacity Riots',
    description: 'A vertical city boils over — autonomous police drones are overwhelmed and garrison units are redirected for urban containment.',
    category: 'player_targeted',
    era_id: 'space_age',
    effect: { type: 'units_removed', target: 'player', value: 2 },
  },
  {
    card_id: 'sa_space_treaty',
    title: 'Outer Space Treaty Revival',
    description: 'Spacefaring powers sign a new non-aggression framework. A temporary ceasefire takes effect with a rival.',
    category: 'player_targeted',
    era_id: 'space_age',
    effect: { type: 'truce', target: 'player', value: 2 },
  },
  {
    card_id: 'sa_terraforming',
    title: 'Terraforming Initiative',
    description: 'Large-scale atmospheric seeding stabilizes a climate-stressed region. Population confidence surges.',
    category: 'player_targeted',
    era_id: 'space_age',
    effect: { type: 'stability_change', target: 'player', value: 20 },
  },
  {
    card_id: 'sa_corp_takeover',
    title: 'Corporate Acquisition',
    description: 'A hostile corporate merger folds a rival\'s security contractor into your command structure. Choose: bonus units or long-term attack contract.',
    category: 'player_targeted',
    era_id: 'space_age',
    choices: [
      { choice_id: 'mercs', label: 'Deploy mercenary brigade (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
      { choice_id: 'contract', label: 'Long-term contract (+1 attack die for 3 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'sa_launch_window',
    title: 'Favorable Launch Window',
    description: 'Orbital mechanics align for an ideal lunar insertion. Choose: accelerated production or a defensive surge.',
    category: 'player_targeted',
    era_id: 'space_age',
    choices: [
      { choice_id: 'production', label: 'Accelerated launches (+3 production for 2 turns)', effect: { type: 'production_bonus', target: 'player', value: 3, duration_turns: 2 } },
      { choice_id: 'defense', label: 'Defensive orbital net (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
];
