import type { EventCard } from '../../../types';

export const ww2Events: EventCard[] = [
  {
    card_id: 'ww2_blitz',
    title: 'Blitzkrieg Offensive',
    description: 'A lightning strike grants +1 attack die for 2 turns.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'ww2_bombing_raid',
    title: 'Strategic Bombing',
    description: 'Enemy bombing raids cost you 3 units.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'ww2_lend_lease',
    title: 'Lend-Lease Act',
    description: 'Allied supplies arrive. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'ww2_war_bonds',
    title: 'War Bonds',
    description: 'Citizens invest in the war effort. Production bonus for 3 turns.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 },
  },
  {
    card_id: 'ww2_winter',
    title: 'Harsh Winter',
    description: 'A brutal winter weakens all armies on the front.',
    category: 'global',
    era_id: 'ww2',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'ww2_enigma',
    title: 'Intelligence Breakthrough',
    description: 'Choose: use decrypted intel offensively or defensively.',
    category: 'player_targeted',
    era_id: 'ww2',
    choices: [
      { choice_id: 'attack', label: 'Offensive intel (+1 attack die for 3 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'defense', label: 'Defensive intel (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'ww2_blitz_doctrine',
    title: 'Blitz Doctrine',
    description: 'High command debates the next strategic move. Launch a devastating armored spearhead, or dig in with layered defenses to bleed the enemy dry.',
    category: 'player_targeted',
    era_id: 'ww2',
    choices: [
      { choice_id: 'attack', label: 'Armored spearhead (+2 attack dice for 1 turn)', effect: { type: 'attack_modifier', target: 'player', value: 2, duration_turns: 1 } },
      { choice_id: 'defense', label: 'Defense in depth (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'ww2_supply_convoy',
    title: 'Supply Convoy Arrives',
    description: 'A massive convoy breaks through enemy blockades, delivering fresh troops, ammunition, and armor to your front lines. Gain 5 reinforcements.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_added', target: 'player', value: 5 },
  },
  {
    card_id: 'ww2_carpet_bombing',
    title: 'Carpet Bombing',
    description: 'Wave after wave of heavy bombers obliterate your positions. Factories burn, supply lines are severed, and 3 units are lost in the devastation.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'ww2_resistance_fighters',
    title: 'Resistance Fighters',
    description: 'Brave partisans operating behind enemy lines sabotage supply depots and relay vital intelligence, bolstering your defensive capabilities for 2 turns.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'ww2_allied_landing',
    title: 'Allied Landing',
    description: 'Amphibious forces storm the beaches under heavy fire. Commit a massive invasion force to seize territory, or use the beachhead to launch precision strikes inland.',
    category: 'player_targeted',
    era_id: 'ww2',
    choices: [
      { choice_id: 'units', label: 'Full invasion force (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
      { choice_id: 'attack', label: 'Precision strikes (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'ww2_winter_offensive',
    title: 'Winter Offensive',
    description: 'A brutal winter descends on the front. Blizzards freeze engines, frostbite claims soldiers, and all armies across the theater suffer losses.',
    category: 'global',
    era_id: 'ww2',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
];
