import type { EventCard } from '../../../types';

export const ww2Events: EventCard[] = [
  {
    card_id: 'ww2_blitz',
    title: 'Blitzkrieg Offensive',
    description: 'A lightning strike grants +1 attack die for 2 turns.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'ww2_bombing_raid',
    title: 'Strategic Bombing',
    description: 'Enemy bombing raids cost you 3 units.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'ww2_lend_lease',
    title: 'Lend-Lease Act',
    description: 'Allied supplies arrive. Gain 4 reinforcements.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_added', target: 'player', value: 4 },
  },
  {
    card_id: 'ww2_war_bonds',
    title: 'War Bonds',
    description: 'Citizens invest in the war effort. Production bonus for 3 turns.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'production_bonus', target: 'player', value: 2, duration_turns: 3 },
  },
  {
    card_id: 'ww2_winter',
    title: 'Harsh Winter',
    description: 'A brutal winter weakens all armies on the front.',
    category: 'global',
    era_id: 'ww2',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'ww2_enigma',
    title: 'Intelligence Breakthrough',
    description: 'Choose: use decrypted intel offensively or defensively.',
    category: 'player_targeted',
    era_id: 'ww2',
    choices: [
      { choice_id: 'attack', label: 'Offensive intel (+1 attack die for 3 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 3 } },
      { choice_id: 'defense', label: 'Defensive intel (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'ww2_blitz_doctrine',
    title: 'Blitz Doctrine',
    description: 'The maps are out at high command. Punch through with armor, or dig in and make them pay for every mile.',
    category: 'player_targeted',
    era_id: 'ww2',
    choices: [
      { choice_id: 'attack', label: 'Armored spearhead (+2 attack dice for 1 turn)', effect: { type: 'attack_modifier', target: 'player', value: 2, duration_turns: 1 } },
      { choice_id: 'defense', label: 'Defense in depth (+1 defense die for 3 turns)', effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 3 } },
    ],
  },
  {
    card_id: 'ww2_supply_convoy',
    title: 'Supply Convoy Arrives',
    description: 'The Murmansk run gets through, wolfpacks be damned. Gain 5 reinforcements.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_added', target: 'player', value: 5 },
  },
  {
    card_id: 'ww2_carpet_bombing',
    title: 'Carpet Bombing',
    description: 'The bombers come back for the third night running. The firestorm over the Ruhr takes 3 units with it.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'units_removed', target: 'player', value: 3 },
  },
  {
    card_id: 'ww2_resistance_fighters',
    title: 'Resistance Fighters',
    description: 'The maquis blow a rail bridge and radio in what they saw. You hold steadier for 2 turns.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'defense_modifier', target: 'player', value: 1, duration_turns: 2 },
  },
  {
    card_id: 'ww2_allied_landing',
    title: 'Allied Landing',
    description: 'The first wave is ashore and the beachhead holds. Pour everything onto it, or push fast and hit hard inland.',
    category: 'player_targeted',
    era_id: 'ww2',
    choices: [
      { choice_id: 'units', label: 'Full invasion force (+4 units)', effect: { type: 'units_added', target: 'player', value: 4 } },
      { choice_id: 'attack', label: 'Precision strikes (+1 attack die for 2 turns)', effect: { type: 'attack_modifier', target: 'player', value: 1, duration_turns: 2 } },
    ],
  },
  {
    card_id: 'ww2_winter_offensive',
    title: 'Winter Offensive',
    description: 'General Winter has joined the war, and he is on nobody’s side. Every army on the front loses men.',
    category: 'global',
    era_id: 'ww2',
    effect: { type: 'region_disaster', target: 'region', value: 1 },
    affects_all_players: true,
  },
  {
    card_id: 'ww2_home_front_rally',
    title: 'Home Front Rally',
    description: 'The scrap drives are overflowing and the bond rallies sell out by noon. Morale at home has rarely been higher.',
    category: 'player_targeted',
    era_id: 'ww2',
    effect: { type: 'stability_change', target: 'player', value: 15 },
  },
  {
    card_id: 'ww2_war_weariness',
    title: 'War Weariness',
    description: 'The casualty lists are longer than the victory bulletins now, and every home front knows it. Governments everywhere lose their grip.',
    category: 'global',
    era_id: 'ww2',
    effect: { type: 'stability_change', target: 'player', value: -10 },
    affects_all_players: true,
  },
];
