/**
 * Build territory→admin-1 mapping for community_australia_1337 globe geometry.
 *
 * Reads the pre-extracted NE 10m admin-1 GeoJSON from public/geo/australia_1337_admin1.json
 * (generated via mapshaper from NE 10m shapefile) and generates the TS mapping file.
 *
 * Run:  pnpm -C frontend exec tsx scripts/buildCommunityAustralia1337Geo.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import bboxPolygon from '@turf/bbox-polygon';
import booleanIntersects from '@turf/boolean-intersects';
import type { Feature, FeatureCollection, MultiPolygon, Polygon } from 'geojson';

/** Territory bounding boxes from community_australia_1337.json geo_polygon extents (with ~0.5° padding) */
const TERRITORIES: { id: string; w: number; s: number; e: number; n: number }[] = [
  { id: 'miwatj_mala', w: 130.3, s: -15.0, e: 137.2, n: -10.7 },
  { id: 'kulaburtan', w: 121.7, s: -18.5, e: 132.5, n: -11.5 },
  { id: 'yurpnanawirrudjan', w: 130.5, s: -20.5, e: 140.5, n: -13.0 },
  { id: 'challbi', w: 139.5, s: -20.5, e: 147.0, n: -10.2 },
  { id: 'gulf_nations', w: 136.5, s: -26.5, e: 148.5, n: -16.5 },
  { id: 'mulyabaj_ura', w: 121.7, s: -28.5, e: 132.5, n: -17.4 },
  { id: 'mulleraladi', w: 113.5, s: -32.5, e: 123.5, n: -16.5 },
  { id: 'noongar', w: 114.5, s: -35.5, e: 120.5, n: -31.4 },
  { id: 'arrernte', w: 128.5, s: -26.5, e: 140.5, n: -17.5 },
  { id: 'pitjantjatjara', w: 125.5, s: -31.5, e: 136.5, n: -23.5 },
  { id: 'kulkanth', w: 134.5, s: -33.5, e: 146.5, n: -22.5 },
  { id: 'dharumbal', w: 144.5, s: -24.5, e: 151.0, n: -18.0 },
  { id: 'waka_waka', w: 147.5, s: -28.0, e: 153.5, n: -22.9 },
  { id: 'yuggera', w: 150.5, s: -29.0, e: 154.0, n: -26.5 },
  { id: 'kamilaroi', w: 148.5, s: -34.4, e: 153.0, n: -24.5 },
  { id: 'gamilaraay', w: 142.5, s: -33.5, e: 149.5, n: -24.5 },
  { id: 'wiradjuri', w: 144.5, s: -37.5, e: 150.5, n: -30.5 },
  { id: 'dharawal', w: 149.5, s: -36.0, e: 152.5, n: -32.5 },
  { id: 'birabak', w: 139.5, s: -39.5, e: 149.0, n: -35.5 },
  { id: 'kaurna', w: 138.1, s: -38.0, e: 146.5, n: -29.5 },
  { id: 'ngargumad', w: 129.5, s: -35.5, e: 140.5, n: -28.5 },
  { id: 'dirillo', w: 118.5, s: -35.0, e: 131.5, n: -26.5 },
  { id: 'te_ika_a_maui', w: 173.5, s: -41.5, e: 178.5, n: -34.5 },
  { id: 'te_waipounamu', w: 166.0, s: -47.5, e: 174.5, n: -41.5 },
  // Islands — no admin-1, use fill_country_iso or keep geo_polygon fallback
  { id: 'tui_manua', w: 181.5, s: -15.5, e: 184.5, n: -12.5 },
  { id: 'tonga', w: 183.5, s: -21.5, e: 185.5, n: -17.5 },
];

/** Territories with no admin-1 coverage — skip (they'll use geo_polygon fallback on the globe) */
const SKIP_ADMIN1 = new Set(['tui_manua', 'tonga']);

/**
 * Manual admin-1 overrides where bbox intersection misses features
 * or where we want explicit assignment.
 */
const MANUAL_ADMIN1: Record<string, string[]> = {
  // Tasmania might be missed if bbox is tight
  birabak: ['AU-TAS'],
};

function codesFor(
  geo: FeatureCollection<Polygon | MultiPolygon>,
  bbox: [number, number, number, number],
): string[] {
  const bp = bboxPolygon(bbox);
  const codes = new Set<string>();
  for (const f of geo.features) {
    const iso = (f.properties as Record<string, unknown>)?.['iso_3166_2'];
    if (typeof iso !== 'string') continue;
    try {
      if (booleanIntersects(f as Feature<Polygon | MultiPolygon>, bp)) codes.add(iso);
    } catch {
      /* skip */
    }
  }
  return [...codes].sort();
}

async function main() {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const geoPath = path.join(__dirname, '../public/geo/australia_1337_admin1.json');
  console.log('Reading', geoPath);
  const subsetFC = JSON.parse(fs.readFileSync(geoPath, 'utf8')) as FeatureCollection<Polygon | MultiPolygon>;
  console.log(`  ${subsetFC.features.length} features`);

  const lines: string[] = [
    '/**',
    ' * "Australia 1337" — globe geometry from Natural Earth ne_10m admin-1 (see public/geo/australia_1337_admin1.json),',
    ' * union admin-1 regions + clip to territory bbox for coastline-accurate globe rendering.',
    ' *',
    ' * Generated by: pnpm -C frontend exec tsx scripts/buildCommunityAustralia1337Geo.ts',
    ' */',
    '',
    "import type { ClipBbox } from './territoryGeoMapping';",
    '',
    'export interface CommunityAustralia1337GeoDef {',
    '  admin1: string[];',
    '  clip_bbox: ClipBbox;',
    '  /** Clip entire country polygon (admin-0) for islands without admin-1. */',
    '  fill_country_iso?: string;',
    '}',
    '',
    'export const COMMUNITY_AUSTRALIA_1337_TERRITORY_GEO: Record<string, CommunityAustralia1337GeoDef> = {',
  ];

  for (const t of TERRITORIES) {
    if (SKIP_ADMIN1.has(t.id)) continue;

    const bbox: [number, number, number, number] = [t.w, t.s, t.e, t.n];
    const auto = codesFor(subsetFC, bbox);
    const manual = MANUAL_ADMIN1[t.id] ?? [];
    const merged = new Set([...auto, ...manual]);
    const admin1 = [...merged].sort();

    if (admin1.length === 0) {
      console.warn(`WARN: ${t.id} — no admin-1 features found, will use geo_polygon fallback`);
      continue;
    }

    lines.push(
      `  ${JSON.stringify(t.id)}: { admin1: ${JSON.stringify(admin1)}, clip_bbox: [${t.w}, ${t.s}, ${t.e}, ${t.n}] },`,
    );
  }

  lines.push('};', '');

  const tsOut = path.join(__dirname, '../src/data/communityAustralia1337Geo.ts');
  fs.writeFileSync(tsOut, lines.join('\n'), 'utf8');
  console.log('Wrote', tsOut);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
