#!/usr/bin/env tsx
/**
 * Generate Voronoi-based clip polygons for the Britain 925 map.
 *
 * Usage: pnpm -C frontend exec tsx scripts/buildBritain925Voronoi.ts
 * Outputs: frontend/src/data/britain925VoronoiClip.ts
 */

import voronoi from '@turf/voronoi';
import { featureCollection, point } from '@turf/helpers';
import buffer from '@turf/buffer';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

import { COMMUNITY_BRITAIN_925_TERRITORY_GEO } from '../src/data/communityBritain925Geo';

const entries = Object.entries(COMMUNITY_BRITAIN_925_TERRITORY_GEO);
const points = entries.map(([id, def]) => {
  const [w, s, e, n] = def.clip_bbox;
  return point([(w + e) / 2, (s + n) / 2], { territory_id: id });
});

const allLngs = entries.flatMap(([, d]) => [d.clip_bbox[0], d.clip_bbox[2]]);
const allLats = entries.flatMap(([, d]) => [d.clip_bbox[1], d.clip_bbox[3]]);
const margin = 3;
const overallBbox: [number, number, number, number] = [
  Math.min(...allLngs) - margin,
  Math.min(...allLats) - margin,
  Math.max(...allLngs) + margin,
  Math.max(...allLats) + margin,
];

const fc = featureCollection(points);
const voronoiResult = voronoi(fc, { bbox: overallBbox });

if (!voronoiResult) {
  console.error('Voronoi generation failed');
  process.exit(1);
}

// Smaller buffer for Britain since territories are dense and close together
const BUFFER_KM = 3;
const clipPolygons: Record<string, number[][][]> = {};

for (let i = 0; i < entries.length; i++) {
  const [id] = entries[i];
  const cell = voronoiResult.features[i];
  if (!cell?.geometry) {
    console.warn(`No Voronoi cell for ${id}`);
    continue;
  }
  const buffered = buffer(cell, BUFFER_KM, { units: 'kilometers' });
  clipPolygons[id] = (buffered?.geometry ?? cell.geometry).coordinates;
}

const outPath = path.join(__dirname, '..', 'src', 'data', 'britain925VoronoiClip.ts');
const lines: string[] = [
  '/**',
  ' * Voronoi-based clip polygons for the Britain 925 map.',
  ' * Replaces rectangular clip_bbox with organic borders between adjacent territories.',
  ' *',
  ' * Generated by: pnpm -C frontend exec tsx scripts/buildBritain925Voronoi.ts',
  ' * DO NOT EDIT MANUALLY.',
  ' */',
  '',
  'export const BRITAIN_925_VORONOI_CLIP: Record<string, number[][][]> = {',
];

for (const [id, coords] of Object.entries(clipPolygons)) {
  lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(coords)},`);
}
lines.push('};');
lines.push('');

fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${Object.keys(clipPolygons).length} Voronoi clip polygons to ${outPath}`);
