#!/usr/bin/env tsx
/**
 * Generate Voronoi-based clip polygons for the Strait of Hormuz map.
 *
 * Usage: pnpm -C frontend exec tsx scripts/buildStraitHormuzVoronoi.ts
 *
 * Outputs: frontend/src/data/straitHormuzVoronoiClip.ts
 */

import voronoi from '@turf/voronoi';
import { featureCollection, point } from '@turf/helpers';
import buffer from '@turf/buffer';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

import { COMMUNITY_STRAIT_HORMUZ_TERRITORY_GEO } from '../src/data/communityStraitHormuzGeo';

const entries = Object.entries(COMMUNITY_STRAIT_HORMUZ_TERRITORY_GEO);
const points = entries.map(([id, def]) => {
  const [w, s, e, n] = def.clip_bbox;
  return point([(w + e) / 2, (s + n) / 2], { territory_id: id });
});

const allLngs = entries.flatMap(([, d]) => [d.clip_bbox[0], d.clip_bbox[2]]);
const allLats = entries.flatMap(([, d]) => [d.clip_bbox[1], d.clip_bbox[3]]);
const margin = 3;
const overallBbox: [number, number, number, number] = [
  Math.min(...allLngs) - margin,
  Math.min(...allLats) - margin,
  Math.max(...allLngs) + margin,
  Math.max(...allLats) + margin,
];

const fc = featureCollection(points);
const voronoiResult = voronoi(fc, { bbox: overallBbox });

if (!voronoiResult) {
  console.error('Voronoi generation failed');
  process.exit(1);
}

const BUFFER_KM = 3;
const clipPolygons: Record<string, number[][][]> = {};

for (let i = 0; i < entries.length; i++) {
  const [id] = entries[i];
  const cell = voronoiResult.features[i];
  if (!cell || !cell.geometry) {
    console.warn(`No Voronoi cell for ${id}, falling back to bbox`);
    continue;
  }
  const buffered = buffer(cell, BUFFER_KM, { units: 'kilometers' });
  if (buffered && buffered.geometry) {
    clipPolygons[id] = buffered.geometry.coordinates;
  } else {
    clipPolygons[id] = cell.geometry.coordinates;
  }
}

const outPath = path.join(__dirname, '..', 'src', 'data', 'straitHormuzVoronoiClip.ts');

const lines: string[] = [
  '/**',
  ' * Voronoi-based clip polygons for the Strait of Hormuz map.',
  ' * These replace rectangular clip_bbox cuts with organic, curved borders.',
  ' *',
  ' * Generated by: pnpm -C frontend exec tsx scripts/buildStraitHormuzVoronoi.ts',
  ' * DO NOT EDIT MANUALLY.',
  ' */',
  '',
  'export const STRAIT_HORMUZ_VORONOI_CLIP: Record<string, number[][][]> = {',
];

for (const [id, coords] of Object.entries(clipPolygons)) {
  lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(coords)},`);
}

lines.push('};');
lines.push('');

fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${Object.keys(clipPolygons).length} Voronoi clip polygons to ${outPath}`);
