/**
 * Build territory→admin-1 mapping for community_britain_925 globe geometry.
 *
 * Reads the pre-extracted NE 10m admin-1 GeoJSON from public/geo/britain_925_admin1.json
 * and generates the TS mapping file.
 *
 * Run:  pnpm -C frontend exec tsx scripts/buildCommunityBritain925Geo.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import bboxPolygon from '@turf/bbox-polygon';
import booleanIntersects from '@turf/boolean-intersects';
import type { Feature, FeatureCollection, MultiPolygon, Polygon } from 'geojson';

/** Territory bounding boxes from community_britain_925.json geo_polygon extents (with ~0.3° padding) */
const TERRITORIES: { id: string; w: number; s: number; e: number; n: number }[] = [
  { id: 'alba', w: -6.1, s: 55.7, e: -1.7, n: 59.0 },
  { id: 'strathclyde', w: -5.8, s: 54.5, e: -2.2, n: 56.3 },
  { id: 'jorvik', w: -3.8, s: 53.2, e: 0.3, n: 56.1 },
  { id: 'danish_east_anglia', w: -1.3, s: 51.2, e: 2.1, n: 54.0 },
  { id: 'gwynedd', w: -5.1, s: 52.0, e: -3.1, n: 53.7 },
  { id: 'deheubarth', w: -5.6, s: 51.3, e: -3.0, n: 52.8 },
  { id: 'brycheiniog', w: -3.8, s: 51.5, e: -2.5, n: 53.3 },
  { id: 'england', w: -3.8, s: 51.2, e: 0.3, n: 54.0 },
  { id: 'essex', w: -0.8, s: 51.1, e: 1.3, n: 52.2 },
  { id: 'winchester', w: -2.3, s: 50.5, e: 0.2, n: 51.8 },
  { id: 'kent', w: -0.4, s: 50.7, e: 1.7, n: 51.8 },
  { id: 'sussex', w: -1.1, s: 50.4, e: 0.8, n: 51.4 },
  { id: 'wessex', w: -4.8, s: 50.0, e: -1.5, n: 52.4 },
  { id: 'cornwall', w: -6.0, s: 49.7, e: -4.2, n: 51.2 },
];

/**
 * Manual admin-1 assignments. GB has 232 features in NE 10m — the auto bbox
 * intersection will pick up many; we add manual overrides where needed.
 */
const MANUAL_ADMIN1: Record<string, string[]> = {};

function codesFor(
  geo: FeatureCollection<Polygon | MultiPolygon>,
  bbox: [number, number, number, number],
): string[] {
  const bp = bboxPolygon(bbox);
  const codes = new Set<string>();
  for (const f of geo.features) {
    const iso = (f.properties as Record<string, unknown>)?.['iso_3166_2'];
    if (typeof iso !== 'string') continue;
    try {
      if (booleanIntersects(f as Feature<Polygon | MultiPolygon>, bp)) codes.add(iso);
    } catch {
      /* skip */
    }
  }
  return [...codes].sort();
}

async function main() {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const geoPath = path.join(__dirname, '../public/geo/britain_925_admin1.json');
  console.log('Reading', geoPath);
  const subsetFC = JSON.parse(fs.readFileSync(geoPath, 'utf8')) as FeatureCollection<Polygon | MultiPolygon>;
  console.log(`  ${subsetFC.features.length} features`);

  const lines: string[] = [
    '/**',
    ' * "Britain 925" — globe geometry from Natural Earth ne_10m admin-1 (see public/geo/britain_925_admin1.json),',
    ' * union admin-1 regions + clip to territory bbox for coastline-accurate globe rendering.',
    ' *',
    ' * Generated by: pnpm -C frontend exec tsx scripts/buildCommunityBritain925Geo.ts',
    ' */',
    '',
    "import type { ClipBbox } from './territoryGeoMapping';",
    '',
    'export interface CommunityBritain925GeoDef {',
    '  admin1: string[];',
    '  clip_bbox: ClipBbox;',
    '}',
    '',
    'export const COMMUNITY_BRITAIN_925_TERRITORY_GEO: Record<string, CommunityBritain925GeoDef> = {',
  ];

  for (const t of TERRITORIES) {
    const bbox: [number, number, number, number] = [t.w, t.s, t.e, t.n];
    const auto = codesFor(subsetFC, bbox);
    const manual = MANUAL_ADMIN1[t.id] ?? [];
    const merged = new Set([...auto, ...manual]);
    const admin1 = [...merged].sort();

    if (admin1.length === 0) {
      console.warn(`WARN: ${t.id} — no admin-1 features found`);
      continue;
    }

    console.log(`  ${t.id}: ${admin1.length} admin-1 codes`);
    lines.push(
      `  ${JSON.stringify(t.id)}: { admin1: ${JSON.stringify(admin1)}, clip_bbox: [${t.w}, ${t.s}, ${t.e}, ${t.n}] },`,
    );
  }

  lines.push('};', '');

  const tsOut = path.join(__dirname, '../src/data/communityBritain925Geo.ts');
  fs.writeFileSync(tsOut, lines.join('\n'), 'utf8');
  console.log('Wrote', tsOut);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
