#!/usr/bin/env tsx
/**
 * Generate Voronoi-based clip polygons for the 14 Nations map.
 *
 * Instead of rectangular clip_bbox cuts (which produce straight-line borders),
 * this script computes Voronoi cells from territory centroids, producing
 * organic, curved borders between adjacent territories on the globe.
 *
 * Usage: pnpm -C frontend exec tsx scripts/buildCommunity14nVoronoi.ts
 *
 * Outputs: frontend/src/data/community14nVoronoiClip.ts
 */

import voronoi from '@turf/voronoi';
import { featureCollection, point } from '@turf/helpers';
import buffer from '@turf/buffer';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

import { COMMUNITY_14N_TERRITORY_GEO } from '../src/data/community14nAdmin1Map';

// Compute centroid of each territory's clip_bbox
const entries = Object.entries(COMMUNITY_14N_TERRITORY_GEO);
const points = entries.map(([id, def]) => {
  const [w, s, e, n] = def.clip_bbox;
  const lng = (w + e) / 2;
  const lat = (s + n) / 2;
  return point([lng, lat], { territory_id: id });
});

// Overall bounding box for all territories (with margin)
const allLngs = entries.flatMap(([, d]) => [d.clip_bbox[0], d.clip_bbox[2]]);
const allLats = entries.flatMap(([, d]) => [d.clip_bbox[1], d.clip_bbox[3]]);
const margin = 5;
const overallBbox: [number, number, number, number] = [
  Math.min(...allLngs) - margin,
  Math.min(...allLats) - margin,
  Math.max(...allLngs) + margin,
  Math.max(...allLats) + margin,
];

const fc = featureCollection(points);
const voronoiResult = voronoi(fc, { bbox: overallBbox });

if (!voronoiResult) {
  console.error('Voronoi generation failed');
  process.exit(1);
}

// Buffer each Voronoi cell slightly to avoid hairline gaps between territories
const BUFFER_KM = 5; // 5km buffer to prevent gaps

// Build the output mapping: territory_id → Voronoi clip polygon coordinates
const clipPolygons: Record<string, number[][][]> = {};

for (let i = 0; i < entries.length; i++) {
  const [id] = entries[i];
  const cell = voronoiResult.features[i];
  if (!cell || !cell.geometry) {
    console.warn(`No Voronoi cell for ${id}, falling back to bbox`);
    continue;
  }

  // Buffer the cell slightly to prevent gaps
  const buffered = buffer(cell, BUFFER_KM, { units: 'kilometers' });
  if (buffered && buffered.geometry) {
    clipPolygons[id] = buffered.geometry.coordinates;
  } else {
    clipPolygons[id] = cell.geometry.coordinates;
  }
}

// Generate output file
const outPath = path.join(__dirname, '..', 'src', 'data', 'community14nVoronoiClip.ts');

const lines: string[] = [
  '/**',
  ' * Voronoi-based clip polygons for the 14 Nations map.',
  ' * These replace rectangular clip_bbox cuts with organic, curved borders.',
  ' *',
  ' * Generated by: pnpm -C frontend exec tsx scripts/buildCommunity14nVoronoi.ts',
  ' * DO NOT EDIT MANUALLY.',
  ' */',
  '',
  '/**',
  ' * Map from territory_id to GeoJSON Polygon coordinates (exterior ring + optional holes).',
  ' * Each value is the `coordinates` array of a GeoJSON Polygon.',
  ' */',
  'export const COMMUNITY_14N_VORONOI_CLIP: Record<string, number[][][]> = {',
];

for (const [id, coords] of Object.entries(clipPolygons)) {
  lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(coords)},`);
}

lines.push('};');
lines.push('');

fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${Object.keys(clipPolygons).length} Voronoi clip polygons to ${outPath}`);
