#!/usr/bin/env tsx
/**
 * Generate Voronoi-based clip polygons for the Australia 1337 map.
 *
 * Usage: pnpm -C frontend exec tsx scripts/buildAustralia1337Voronoi.ts
 * Outputs: frontend/src/data/australia1337VoronoiClip.ts
 */

import voronoi from '@turf/voronoi';
import { featureCollection, point } from '@turf/helpers';
import buffer from '@turf/buffer';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

import { COMMUNITY_AUSTRALIA_1337_TERRITORY_GEO } from '../src/data/communityAustralia1337Geo';

const entries = Object.entries(COMMUNITY_AUSTRALIA_1337_TERRITORY_GEO);

// Split into geographic clusters: AU mainland vs NZ
// NZ territories need their own Voronoi to avoid a single huge cell spanning the Tasman Sea
const auEntries = entries.filter(([id]) => !id.startsWith('te_'));
const nzEntries = entries.filter(([id]) => id.startsWith('te_'));

function generateVoronoi(
  subset: [string, typeof COMMUNITY_AUSTRALIA_1337_TERRITORY_GEO[string]][],
  margin: number,
  bufferKm: number,
): Record<string, number[][][]> {
  const pts = subset.map(([id, def]) => {
    const [w, s, e, n] = def.clip_bbox;
    return point([(w + e) / 2, (s + n) / 2], { territory_id: id });
  });

  const allLngs = subset.flatMap(([, d]) => [d.clip_bbox[0], d.clip_bbox[2]]);
  const allLats = subset.flatMap(([, d]) => [d.clip_bbox[1], d.clip_bbox[3]]);
  const bbox: [number, number, number, number] = [
    Math.min(...allLngs) - margin,
    Math.min(...allLats) - margin,
    Math.max(...allLngs) + margin,
    Math.max(...allLats) + margin,
  ];

  const fc = featureCollection(pts);
  const result = voronoi(fc, { bbox });
  if (!result) throw new Error('Voronoi generation failed');

  const clips: Record<string, number[][][]> = {};
  for (let i = 0; i < subset.length; i++) {
    const [id] = subset[i];
    const cell = result.features[i];
    if (!cell?.geometry) {
      console.warn(`No Voronoi cell for ${id}`);
      continue;
    }
    const buffered = buffer(cell, bufferKm, { units: 'kilometers' });
    clips[id] = (buffered?.geometry ?? cell.geometry).coordinates;
  }
  return clips;
}

// Australia mainland: larger buffer since territories are big
const auClips = generateVoronoi(auEntries, 5, 10);
// New Zealand: separate Voronoi
const nzClips = generateVoronoi(nzEntries, 3, 5);

const allClips = { ...auClips, ...nzClips };

const outPath = path.join(__dirname, '..', 'src', 'data', 'australia1337VoronoiClip.ts');
const lines: string[] = [
  '/**',
  ' * Voronoi-based clip polygons for the Australia 1337 map.',
  ' * Replaces rectangular clip_bbox with organic borders between adjacent territories.',
  ' *',
  ' * Generated by: pnpm -C frontend exec tsx scripts/buildAustralia1337Voronoi.ts',
  ' * DO NOT EDIT MANUALLY.',
  ' */',
  '',
  'export const AUSTRALIA_1337_VORONOI_CLIP: Record<string, number[][][]> = {',
];

for (const [id, coords] of Object.entries(allClips)) {
  lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(coords)},`);
}
lines.push('};');
lines.push('');

fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${Object.keys(allClips).length} Voronoi clip polygons to ${outPath}`);
