/**
 * Build territory→admin-1 mapping for community_horn_africa globe geometry.
 *
 * Reads the pre-extracted NE 10m admin-1 GeoJSON from public/geo/horn_africa_admin1.json
 * and generates the TS mapping file.
 *
 * Run:  pnpm -C frontend exec tsx scripts/buildCommunityHornAfricaGeo.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import bboxPolygon from '@turf/bbox-polygon';
import booleanIntersects from '@turf/boolean-intersects';
import type { Feature, FeatureCollection, MultiPolygon, Polygon } from 'geojson';

/** Territory bounding boxes from community_horn_africa.json geo_polygon extents (with ~0.5° padding) */
const TERRITORIES: { id: string; w: number; s: number; e: number; n: number; fill?: string }[] = [
  { id: 'aden', w: 44.0, s: 12.0, e: 46.0, n: 13.5 },
  { id: 'lahij', w: 43.5, s: 12.5, e: 46.0, n: 14.5 },
  { id: 'abyan', w: 45.0, s: 12.0, e: 47.0, n: 14.5 },
  { id: 'shabwah', w: 44.5, s: 13.0, e: 48.5, n: 16.5 },
  { id: 'hadhramaut', w: 47.0, s: 13.0, e: 52.0, n: 17.5 },
  { id: 'mahra', w: 50.5, s: 14.0, e: 54.5, n: 18.0 },
  { id: 'eritrea', w: 35.5, s: 14.0, e: 43.5, n: 18.5 },
  { id: 'tigray', w: 35.5, s: 12.0, e: 41.0, n: 16.0 },
  { id: 'begender', w: 35.5, s: 11.0, e: 39.0, n: 15.0 },
  { id: 'afar', w: 39.0, s: 9.5, e: 43.5, n: 16.5 },
  { id: 'wollo', w: 38.0, s: 10.0, e: 40.5, n: 13.5 },
  { id: 'gojjam', w: 35.5, s: 9.5, e: 39.0, n: 12.0 },
  { id: 'shewa', w: 37.0, s: 8.0, e: 40.5, n: 11.5 },
  { id: 'welega', w: 33.5, s: 7.5, e: 38.0, n: 11.0 },
  { id: 'illubabor', w: 33.0, s: 6.0, e: 36.5, n: 9.0 },
  { id: 'kaffa', w: 34.5, s: 5.0, e: 37.5, n: 7.5 },
  { id: 'gamu_gofa', w: 34.5, s: 2.5, e: 38.5, n: 7.0 },
  { id: 'sidamo', w: 37.5, s: 4.5, e: 40.5, n: 8.0 },
  { id: 'arsi', w: 37.5, s: 6.5, e: 41.0, n: 9.5 },
  { id: 'bale', w: 39.0, s: 5.0, e: 42.5, n: 8.5 },
  { id: 'hararghe', w: 39.0, s: 7.5, e: 43.5, n: 12.5 },
  { id: 'hargeisa', w: 42.5, s: 8.5, e: 46.5, n: 13.5 },
  { id: 'soomaali_galbeed', w: 36.5, s: 2.5, e: 46.5, n: 10.0 },
  { id: 'burao', w: 43.5, s: 8.5, e: 48.5, n: 14.7 },
  { id: 'migiurtinia', w: 46.5, s: 6.5, e: 51.5, n: 15.5 },
  { id: 'mudugh', w: 44.5, s: 3.5, e: 50.5, n: 10.0 },
  { id: 'hiran', w: 41.5, s: 1.5, e: 46.5, n: 6.5 },
  { id: 'alto_gubia', w: 36.5, s: -1.0, e: 48.5, n: 5.0 },
  // Socotra island — use fill_country_iso for Yemen admin-0
  { id: 'socotra', w: 52.5, s: 11.5, e: 55.0, n: 13.3, fill: 'YE' },
];

const MANUAL_ADMIN1: Record<string, string[]> = {};

function codesFor(
  geo: FeatureCollection<Polygon | MultiPolygon>,
  bbox: [number, number, number, number],
): string[] {
  const bp = bboxPolygon(bbox);
  const codes = new Set<string>();
  for (const f of geo.features) {
    const iso = (f.properties as Record<string, unknown>)?.['iso_3166_2'];
    if (typeof iso !== 'string') continue;
    try {
      if (booleanIntersects(f as Feature<Polygon | MultiPolygon>, bp)) codes.add(iso);
    } catch {
      /* skip */
    }
  }
  return [...codes].sort();
}

async function main() {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const geoPath = path.join(__dirname, '../public/geo/horn_africa_admin1.json');
  console.log('Reading', geoPath);
  const subsetFC = JSON.parse(fs.readFileSync(geoPath, 'utf8')) as FeatureCollection<Polygon | MultiPolygon>;
  console.log(`  ${subsetFC.features.length} features`);

  const lines: string[] = [
    '/**',
    ' * "Horn of Africa" — globe geometry from Natural Earth ne_10m admin-1 (see public/geo/horn_africa_admin1.json),',
    ' * union admin-1 regions + clip to territory bbox for coastline-accurate globe rendering.',
    ' *',
    ' * Generated by: pnpm -C frontend exec tsx scripts/buildCommunityHornAfricaGeo.ts',
    ' */',
    '',
    "import type { ClipBbox } from './territoryGeoMapping';",
    '',
    'export interface CommunityHornAfricaGeoDef {',
    '  admin1: string[];',
    '  clip_bbox: ClipBbox;',
    '  fill_country_iso?: string;',
    '}',
    '',
    'export const COMMUNITY_HORN_AFRICA_TERRITORY_GEO: Record<string, CommunityHornAfricaGeoDef> = {',
  ];

  for (const t of TERRITORIES) {
    const bbox: [number, number, number, number] = [t.w, t.s, t.e, t.n];
    const auto = codesFor(subsetFC, bbox);
    const manual = MANUAL_ADMIN1[t.id] ?? [];
    const merged = new Set([...auto, ...manual]);
    const admin1 = [...merged].sort();

    if (admin1.length === 0 && !t.fill) {
      console.warn(`WARN: ${t.id} — no admin-1 features found`);
      continue;
    }

    const fillStr = t.fill ? `, fill_country_iso: ${JSON.stringify(t.fill)}` : '';
    console.log(`  ${t.id}: ${admin1.length} admin-1 codes${t.fill ? ' + fill ' + t.fill : ''}`);
    lines.push(
      `  ${JSON.stringify(t.id)}: { admin1: ${JSON.stringify(admin1)}, clip_bbox: [${t.w}, ${t.s}, ${t.e}, ${t.n}]${fillStr} },`,
    );
  }

  lines.push('};', '');

  const tsOut = path.join(__dirname, '../src/data/communityHornAfricaGeo.ts');
  fs.writeFileSync(tsOut, lines.join('\n'), 'utf8');
  console.log('Wrote', tsOut);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
