/**
 * "Horn of Africa" — globe geometry from Natural Earth ne_10m admin-1 (see public/geo/horn_africa_admin1.json),
 * union admin-1 regions + clip to territory bbox for coastline-accurate globe rendering.
 *
 * Generated by: pnpm -C frontend exec tsx scripts/buildCommunityHornAfricaGeo.ts
 */

import type { ClipBbox } from './territoryGeoMapping';

export interface CommunityHornAfricaGeoDef {
  admin1: string[];
  /**
   * Optional bbox clip. Omit when admin-1 codes uniquely match this territory
   * (Option 1: real coastlines + ethnic borders). Provide when multiple
   * territories share an admin-1 polygon (e.g. historical Ethiopian provinces
   * subdividing modern Amhara/Oromia/SNNPR; Ogaden/ET-SO split between
   * Soomaali Galbeed and Burao on the Ethiopia side).
   */
  clip_bbox?: ClipBbox;
  fill_country_iso?: string;
}

/**
 * Hybrid admin-1 design (Option 2):
 * - Coastal Yemen, Eritrea, Somali coast (Puntland, central/south Somalia),
 *   plus Tigray/Afar render the full admin-1 polygon — real coastlines.
 * - Historical Ethiopian provinces (Begender/Gojjam/Wollo carved from ET-AM;
 *   Shewa/Welega/Illubabor/Arsi/Bale carved from ET-OR; Kaffa/Gamu Gofa from
 *   ET-SN; Sidamo from ET-OR + ET-SN; Hararghe from ET-OR + ET-HA + ET-DD)
 *   keep bbox slicing because admin-1 doesn't subdivide them.
 * - Soomaali Galbeed and Burao both lie in ET-SO (Ogaden) and Hargeisa lies
 *   in ET-SO + Djibouti — they retain bbox to subdivide that single admin-1.
 * - Each admin-1 is assigned to a single primary 1:1 territory where one
 *   exists; this eliminates overlapping ownership across territories.
 */
export const COMMUNITY_HORN_AFRICA_TERRITORY_GEO: Record<string, CommunityHornAfricaGeoDef> = {
  // --- Yemen (coastal, 1:1) ---
  "aden": { admin1: ["YE-AD"] },
  "lahij": { admin1: ["YE-LA", "YE-TA", "YE-IB", "YE-DH"] },
  "abyan": { admin1: ["YE-AB", "YE-DA"] },
  "shabwah": { admin1: ["YE-SH", "YE-BA", "YE-MA", "YE-AM", "YE-SN"] },
  // Hadhramaut admin-1 includes Socotra island; bbox clips to mainland.
  "hadhramaut": { admin1: ["YE-HD", "YE-JA"], clip_bbox: [47, 13, 52, 17.5] },
  "mahra": { admin1: ["YE-MR"] },
  "socotra": { admin1: ["YE-HD"], clip_bbox: [52.5, 11.5, 55, 13.3], fill_country_iso: "YE" },

  // --- North-east Africa (1:1) ---
  "eritrea": { admin1: ["ER-AN", "ER-DK", "ER-DU", "ER-GB", "ER-MA", "ER-SK"] },
  "tigray": { admin1: ["ET-TI"] },
  "afar": { admin1: ["ET-AF"] },

  // --- Historical Amhara provinces (carve ET-AM via bbox) ---
  "begender": { admin1: ["ET-AM"], clip_bbox: [35.5, 11, 39, 15] },
  "gojjam": { admin1: ["ET-AM", "ET-BE"], clip_bbox: [35.5, 9.5, 39, 12] },
  "wollo": { admin1: ["ET-AM"], clip_bbox: [38, 10, 40.5, 13.5] },

  // --- Historical Oromia provinces (carve ET-OR via bbox) ---
  "shewa": { admin1: ["ET-AA", "ET-OR"], clip_bbox: [37, 8, 40.5, 11.5] },
  // Tightened: minLng was 33.5 — 0.5° west of ET-OR/ET-BE actual extent (caught Sudan slivers).
  "welega": { admin1: ["ET-OR", "ET-BE"], clip_bbox: [34.0, 7.5, 38, 11] },
  // Tightened: minLng was 33 — touched ET-GA boundary sliver near South Sudan.
  "illubabor": { admin1: ["ET-OR", "ET-GA"], clip_bbox: [33.2, 6, 36.5, 9] },
  "arsi": { admin1: ["ET-OR"], clip_bbox: [37.5, 6.5, 41, 9.5] },
  "bale": { admin1: ["ET-OR"], clip_bbox: [39, 5, 42.5, 8.5] },

  // --- Historical SNNPR provinces (carve ET-SN via bbox) ---
  "kaffa": { admin1: ["ET-SN"], clip_bbox: [34.5, 5, 37.5, 7.5] },
  "gamu_gofa": { admin1: ["ET-SN"], clip_bbox: [34.5, 2.5, 38.5, 7] },
  "sidamo": { admin1: ["ET-OR", "ET-SN"], clip_bbox: [37.5, 4.5, 40.5, 8] },

  // --- Hararghe (Eastern Ethiopia, includes Harari + Dire Dawa) ---
  "hararghe": { admin1: ["ET-HA", "ET-DD", "ET-OR"], clip_bbox: [39, 7.5, 43.5, 12.5] },

  // --- Somaliland & Ogaden (carve ET-SO + DJ codes via bbox) ---
  "hargeisa": {
    admin1: ["ET-SO", "DJ-AR", "DJ-AS", "DJ-DI", "DJ-TA", "DJ-OB", "DJ-DJ"],
    clip_bbox: [42.5, 8.5, 46.5, 13.5],
  },
  // Tightened: minLng was 36.5 — 2.6° west of ET-SO actual min (39.090) caught stray geometry.
  "soomaali_galbeed": { admin1: ["ET-SO"], clip_bbox: [38.5, 2.5, 46.5, 10] },
  // Tightened: maxLat was 14.7 — 3.6° north of ET-SO actual max (11.089) extended into Yemen sea.
  "burao": { admin1: ["ET-SO"], clip_bbox: [43.5, 8.5, 48.5, 11.5] },

  // --- Somalia (1:1 admin-1 unions for non-overlapping regions) ---
  "migiurtinia": { admin1: ["SO-BR", "SO-NU"] },
  "mudugh": { admin1: ["SO-MU", "SO-GA"] },
  "hiran": { admin1: ["SO-HI", "SO-SD"] },
  "alto_gubia": {
    admin1: ["SO-BN", "SO-BY", "SO-BK", "SO-GE", "SO-JD", "SO-JH", "SO-SH"],
  },
};
