/**
 * "Australia 1337" — globe geometry from Natural Earth ne_10m admin-1 (see public/geo/australia_1337_admin1.json),
 * union admin-1 regions + clip to territory bbox for coastline-accurate globe rendering.
 *
 * Generated by: pnpm -C frontend exec tsx scripts/buildCommunityAustralia1337Geo.ts
 */

import type { ClipBbox } from './territoryGeoMapping';

export interface CommunityAustralia1337GeoDef {
  admin1: string[];
  clip_bbox: ClipBbox;
  /** Clip entire country polygon (admin-0) for islands without admin-1. */
  fill_country_iso?: string;
}

export const COMMUNITY_AUSTRALIA_1337_TERRITORY_GEO: Record<string, CommunityAustralia1337GeoDef> = {
  "miwatj_mala": { admin1: ["AU-NT"], clip_bbox: [130.3, -15, 137.2, -10.7] },
  "kulaburtan": { admin1: ["AU-NT","AU-WA","AU-X04~"], clip_bbox: [121.7, -18.5, 132.5, -11.5] },
  "yurpnanawirrudjan": { admin1: ["AU-NT","AU-QLD"], clip_bbox: [130.5, -20.5, 140.5, -13] },
  "challbi": { admin1: ["AU-QLD"], clip_bbox: [139.5, -20.5, 147, -10.2] },
  "gulf_nations": { admin1: ["AU-NT","AU-QLD","AU-SA"], clip_bbox: [136.5, -26.5, 148.5, -16.5] },
  "mulyabaj_ura": { admin1: ["AU-NT","AU-SA","AU-WA"], clip_bbox: [121.7, -28.5, 132.5, -17.4] },
  "mulleraladi": { admin1: ["AU-WA"], clip_bbox: [113.5, -32.5, 123.5, -16.5] },
  "noongar": { admin1: ["AU-WA"], clip_bbox: [114.5, -35.5, 120.5, -31.4] },
  "arrernte": { admin1: ["AU-NT","AU-QLD","AU-SA","AU-WA"], clip_bbox: [128.5, -26.5, 140.5, -17.5] },
  "pitjantjatjara": { admin1: ["AU-NT","AU-SA","AU-WA"], clip_bbox: [125.5, -31.5, 136.5, -23.5] },
  "kulkanth": { admin1: ["AU-NSW","AU-NT","AU-QLD","AU-SA"], clip_bbox: [134.5, -33.5, 146.5, -22.5] },
  "dharumbal": { admin1: ["AU-QLD"], clip_bbox: [144.5, -24.5, 151, -18] },
  "waka_waka": { admin1: ["AU-QLD"], clip_bbox: [147.5, -28, 153.5, -22.9] },
  "yuggera": { admin1: ["AU-NSW","AU-QLD"], clip_bbox: [150.5, -29, 154, -26.5] },
  "kamilaroi": { admin1: ["AU-NSW","AU-QLD"], clip_bbox: [148.5, -34.4, 153, -24.5] },
  "gamilaraay": { admin1: ["AU-NSW","AU-QLD"], clip_bbox: [142.5, -33.5, 149.5, -24.5] },
  "wiradjuri": { admin1: ["AU-ACT","AU-NSW","AU-VIC"], clip_bbox: [144.5, -37.5, 150.5, -30.5] },
  "dharawal": { admin1: ["AU-NSW","AU-X02~"], clip_bbox: [149.5, -36, 152.5, -32.5] },
  "birabak": { admin1: ["AU-ACT","AU-NSW","AU-SA","AU-TAS","AU-VIC"], clip_bbox: [139.5, -39.5, 149, -35.5] },
  "kaurna": { admin1: ["AU-NSW","AU-SA","AU-VIC"], clip_bbox: [138.1, -38, 146.5, -29.5] },
  "ngargumad": { admin1: ["AU-SA"], clip_bbox: [129.5, -35.5, 140.5, -28.5] },
  "dirillo": { admin1: ["AU-SA","AU-WA"], clip_bbox: [118.5, -35, 131.5, -26.5] },
  "te_ika_a_maui": { admin1: ["NZ-AUK","NZ-BOP","NZ-GIS","NZ-HKB","NZ-MBH","NZ-MWT","NZ-NSN","NZ-NTL","NZ-TKI","NZ-WGN","NZ-WKO"], clip_bbox: [173.5, -41.5, 178.5, -34.5] },
  "te_waipounamu": { admin1: ["NZ-CAN","NZ-MBH","NZ-OTA","NZ-STL","NZ-TAS","NZ-WTC"], clip_bbox: [166, -47.5, 174.5, -41.5] },
};
