/**
 * The committed Galactic Age files must be exactly what the world specs build.
 *
 * `database/maps/era_galaxy.json` (and its public copy) and the two globe data
 * modules are generated by `scripts/buildGalaxyWorlds.ts` from
 * `scripts/galaxy/worldSpecs.ts`. Before this test existed, the 16-region split
 * lived only in hand edits to the map file, so re-running the generator
 * silently moved every territory into regions the map no longer declared —
 * emptying the Nexus Vault and breaking the one-faction-per-world start.
 *
 * Comparing BYTES is deliberate: a test that re-derived and compared values
 * could pass while a committed file was wrong.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { generateGalaxyWorlds, validateGalaxySpecs, type GalaxyMapScaffold } from '../../scripts/galaxy/generateGalaxyWorlds';
import { GALAXY_SPECS, type GalaxySpecs } from '../../scripts/galaxy/worldSpecs';
import { GALAXY_OUTPUT_PATHS } from '../../scripts/buildGalaxyWorlds';

const STALE = 'stale — run: pnpm -C frontend exec tsx scripts/buildGalaxyWorlds.ts';
const scaffold = JSON.parse(readFileSync(GALAXY_OUTPUT_PATHS.map, 'utf8')) as GalaxyMapScaffold;
const out = generateGalaxyWorlds(scaffold, GALAXY_SPECS);
const worldIds = (scaffold.worlds ?? []).map((w) => w.world_id);

describe('galaxy world files', () => {
  it.each([
    ['era_galaxy.json', GALAXY_OUTPUT_PATHS.map, () => out.mapJson],
    ['public era_galaxy.json', GALAXY_OUTPUT_PATHS.publicMap, () => out.mapJson],
    ['galaxyExoVoronoiGlobe.ts', GALAXY_OUTPUT_PATHS.exoGlobe, () => out.exoGlobeModule],
    ['galaxySolGlobeGeo.ts', GALAXY_OUTPUT_PATHS.solGeo, () => out.solGeoModule],
  ])('%s matches the specs', (_label, file, expected) => {
    expect(readFileSync(file, 'utf8') === expected() ? true : STALE).toBe(true);
  });

  it('gives every region at least one territory, all on one world', () => {
    const worldsOf = new Map<string, Set<string>>();
    for (const t of out.map.territories) {
      const set = worldsOf.get(t.region_id) ?? new Set<string>();
      set.add(t.world_id);
      worldsOf.set(t.region_id, set);
    }
    const regions = out.map.regions as Array<{ region_id: string }>;
    for (const r of regions) expect(worldsOf.get(r.region_id)?.size, r.region_id).toBe(1);
  });
});

describe('validateGalaxySpecs', () => {
  const clone = (): GalaxySpecs => JSON.parse(JSON.stringify(GALAXY_SPECS));

  it('accepts the shipped specs', () => {
    expect(() => validateGalaxySpecs(GALAXY_SPECS, worldIds)).not.toThrow();
  });

  it('rejects a territory in an undeclared region', () => {
    const s = clone();
    s.farWorlds[0].territories[0].region_id = 'verdant_expanse';
    expect(() => validateGalaxySpecs(s, worldIds)).toThrow(/region verdant_expanse is not declared/);
  });

  it("rejects a territory in another world's region", () => {
    const s = clone();
    s.farWorlds[0].territories[0].region_id = 'rust_foundry_core';
    expect(() => validateGalaxySpecs(s, worldIds)).toThrow(/belongs to rust, not verdan/);
  });

  it('rejects a declared region with no territories', () => {
    const s = clone();
    s.farWorlds[0].regions.push({ region_id: 'verdan_empty', name: 'Empty', bonus: 1 });
    expect(() => validateGalaxySpecs(s, worldIds)).toThrow(/region verdan_empty has no territories/);
  });

  it('rejects a lane to a missing territory, a tile on two lanes, and a lane inside one world', () => {
    const s = clone();
    s.lanes.push({ from: 'sol_columbia', to: 'verdan_nowhere' });
    s.lanes.push({ from: 'sol_guinea', to: 'rust_cinderworks' });
    s.lanes.push({ from: 'rust_oxide_flats', to: 'rust_dross_hollow' });
    expect(() => validateGalaxySpecs(s, worldIds)).toThrow(/verdan_nowhere is not a territory/);
    expect(() => validateGalaxySpecs(s, worldIds)).toThrow(/sol_guinea ends more than one lane/);
    expect(() => validateGalaxySpecs(s, worldIds)).toThrow(/rust_oxide_flats–rust_dross_hollow does not leave its world/);
  });

  it('rejects a far world the map does not declare', () => {
    expect(() => validateGalaxySpecs(GALAXY_SPECS, ['sol', 'verdan', 'rust'])).toThrow(/nexus_station has no worlds\[\] entry/);
  });
});
