/**
 * Galactic Age — Sol III globe geometry.
 *
 * Reuses the Space Age Earth admin-0 partition (Natural Earth clips) so Sol III
 * renders with real coastlines. Each Sol territory aggregates several
 * `TERRITORY_GEO_CONFIG` entries; together they tile the planet without overlap.
 *
 * Generated by: pnpm -C frontend exec tsx scripts/buildGalaxyWorlds.ts
 * DO NOT EDIT MANUALLY.
 */

import type { TerritoryGeoConfig } from './territoryGeoMapping';
import { TERRITORY_GEO_CONFIG } from './territoryGeoMapping';

function mergeConfigs(...keys: (keyof typeof TERRITORY_GEO_CONFIG)[]): TerritoryGeoConfig {
  const out: TerritoryGeoConfig = [];
  for (const k of keys) {
    const chunk = TERRITORY_GEO_CONFIG[k];
    if (chunk?.length) out.push(...chunk);
  }
  return out;
}

export const GALAXY_SOL_TERRITORY_GEO: Record<string, TerritoryGeoConfig> = {
  sol_columbia: mergeConfigs('na_eastern_corridor', 'na_launch_base', 'na_southern_belt', 'la_caribbean'),
  sol_pacifica: mergeConfigs('na_western_states', 'na_central_plains', 'na_arctic_dominion'),
  sol_atlantic_europe: mergeConfigs('euro_british_isles', 'euro_iberia', 'euro_nordic'),
  sol_eastern_reach: mergeConfigs('euro_balkan', 'euro_spaceport', 'euro_east'),
  sol_maghreb: mergeConfigs('mena_maghreb', 'mena_nile', 'mena_levant'),
  sol_arabia: mergeConfigs('mena_arabia', 'mena_persia'),
  sol_guinea: mergeConfigs('africa_west', 'africa_sahel'),
  sol_equatoria: mergeConfigs('africa_congo_basin', 'africa_horn', 'africa_east'),
  sol_austral: mergeConfigs('africa_south'),
  sol_turkestan: mergeConfigs('ca_steppe', 'ca_tien_shan', 'asia_siberia_belt'),
  sol_hindustan: mergeConfigs('ca_indus', 'ca_ganges', 'ca_deccan'),
  sol_cathay: mergeConfigs('asia_cosmodrome', 'asia_heartland', 'asia_coastal'),
  sol_pacific_rim: mergeConfigs('asia_korea_archipelago', 'asia_japan_islands', 'asia_indochina', 'asia_malay_archipelago', 'megacity_pacific_rim'),
  sol_oceania: mergeConfigs('oc_australia', 'oc_new_zealand', 'oc_micronesia', 'oc_polynesia'),
  sol_amazonia: mergeConfigs('la_amazonia', 'la_andes'),
  sol_southern_cone: mergeConfigs('la_pampas', 'la_patagonia'),
};
