"""
Napoleonic Europe — 1812 — generated map. Voronoi tessellation of province seeds, each clipped to its
overlapping modern country geometry for real coastlines and organic, gap-free borders.
Connections are derived from Voronoi adjacency (land/sea typed by the shared border).
Reproducible via mapkit.voronoi_cells; per-cell country lists + connections baked.
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from mapkit import build_map, voronoi_cells

BOUNDS = {"minLng": -11.0, "maxLng": 40.0, "minLat": 35.5, "maxLat": 61.0}
REGIONS = [
    {"region_id": "france", "name": "French Empire", "bonus": 6},
    {"region_id": "iberia", "name": "Iberia", "bonus": 4},
    {"region_id": "italia", "name": "Italia", "bonus": 4},
    {"region_id": "germania", "name": "Confederation of the Rhine", "bonus": 5},
    {"region_id": "austria", "name": "Austrian Empire", "bonus": 5},
    {"region_id": "prussia_poland", "name": "Prussia & Warsaw", "bonus": 4},
    {"region_id": "russia", "name": "Russian Empire", "bonus": 5},
    {"region_id": "britannia_nord", "name": "Britain & the North", "bonus": 5},
    {"region_id": "balkans", "name": "The Balkans", "bonus": 3},
]
SEEDS = [
    ("ile_de_france", "Île-de-France", "france", [2.4, 48.8]),
    ("normandy_brittany", "Normandy & Brittany", "france", [-1.6, 48.2]),
    ("aquitaine", "Aquitaine", "france", [0.4, 44.6]),
    ("provence", "Provence", "france", [5.6, 43.9]),
    ("lyonnais", "Lyonnais", "france", [4.5, 46.0]),
    ("alsace_lorraine", "Alsace-Lorraine", "france", [6.4, 48.6]),
    ("belgium", "Belgium", "france", [4.3, 50.6]),
    ("castile", "Castile", "iberia", [-3.7, 40.4]),
    ("catalonia", "Catalonia", "iberia", [1.4, 41.8]),
    ("andalusia", "Andalusia", "iberia", [-4.6, 37.4]),
    ("galicia_leon", "Galicia & León", "iberia", [-6.6, 42.5]),
    ("portugal", "Portugal", "iberia", [-8.2, 39.7]),
    ("piedmont", "Piedmont", "italia", [7.7, 45.0]),
    ("kingdom_italy", "Kingdom of Italy", "italia", [10.6, 45.2]),
    ("central_italy", "Central Italy", "italia", [12.2, 43.2]),
    ("naples", "Kingdom of Naples", "italia", [15.4, 41.0]),
    ("sicily", "Sicily", "italia", [14.2, 37.5]),
    ("westphalia", "Westphalia", "germania", [8.6, 51.6]),
    ("hanover", "Hanover", "germania", [9.8, 52.7]),
    ("rhineland", "Rhineland", "germania", [7.8, 50.2]),
    ("wurttemberg", "Württemberg & Baden", "germania", [9.1, 48.4]),
    ("bavaria", "Bavaria", "germania", [11.6, 48.8]),
    ("saxony", "Saxony", "germania", [13.2, 51.1]),
    ("austria_core", "Austria", "austria", [15.3, 47.7]),
    ("bohemia", "Bohemia", "austria", [15.0, 49.8]),
    ("hungary", "Hungary", "austria", [19.5, 47.2]),
    ("illyria", "Illyria", "austria", [15.2, 45.8]),
    ("galicia_aus", "Galicia", "austria", [22.5, 49.5]),
    ("prussia", "Prussia", "prussia_poland", [13.2, 52.6]),
    ("east_prussia", "East Prussia", "prussia_poland", [20.6, 54.0]),
    ("warsaw", "Duchy of Warsaw", "prussia_poland", [20.2, 52.1]),
    ("lithuania", "Lithuania", "russia", [25.5, 55.2]),
    ("west_russia", "White Russia", "russia", [30.0, 53.5]),
    ("ukraine", "Ukraine", "russia", [32.0, 49.5]),
    ("moscow", "Muscovy", "russia", [37.5, 55.6]),
    ("st_petersburg", "St. Petersburg", "russia", [31.0, 59.5]),
    ("england", "England & Wales", "britannia_nord", [-1.8, 52.6]),
    ("scotland", "Scotland", "britannia_nord", [-4.2, 56.9]),
    ("ireland", "Ireland", "britannia_nord", [-8.0, 53.3]),
    ("denmark", "Denmark", "britannia_nord", [9.6, 56.2]),
    ("sweden", "Sweden", "britannia_nord", [15.0, 59.5]),
    ("rumelia", "Ottoman Rumelia", "balkans", [25.5, 42.2]),
    ("greece", "Greece & the Morea", "balkans", [22.5, 38.5]),
    ("wallachia", "Wallachia & Moldavia", "balkans", [26.0, 45.3]),
]
CONNECTIONS = [
    ("andalusia", "portugal", "land"),
    ("andalusia", "catalonia", "sea"),
    ("catalonia", "sicily", "land"),
    ("greece", "sicily", "sea"),
    ("greece", "rumelia", "land"),
    ("rumelia", "ukraine", "land"),
    ("provence", "sicily", "sea"),
    ("catalonia", "provence", "sea"),
    ("andalusia", "castile", "land"),
    ("castile", "catalonia", "land"),
    ("naples", "sicily", "sea"),
    ("greece", "naples", "sea"),
    ("central_italy", "sicily", "sea"),
    ("central_italy", "provence", "land"),
    ("castile", "portugal", "land"),
    ("central_italy", "naples", "sea"),
    ("galicia_leon", "portugal", "land"),
    ("castile", "galicia_leon", "land"),
    ("piedmont", "provence", "sea"),
    ("central_italy", "piedmont", "land"),
    ("aquitaine", "catalonia", "land"),
    ("aquitaine", "castile", "land"),
    ("greece", "hungary", "land"),
    ("central_italy", "kingdom_italy", "land"),
    ("hungary", "naples", "land"),
    ("kingdom_italy", "piedmont", "land"),
    ("rumelia", "wallachia", "land"),
    ("hungary", "rumelia", "land"),
    ("ukraine", "wallachia", "land"),
    ("central_italy", "illyria", "sea"),
    ("illyria", "naples", "land"),
    ("hungary", "illyria", "land"),
    ("lyonnais", "provence", "land"),
    ("aquitaine", "lyonnais", "land"),
    ("aquitaine", "galicia_leon", "sea"),
    ("hungary", "wallachia", "land"),
    ("galicia_leon", "normandy_brittany", "sea"),
    ("aquitaine", "normandy_brittany", "sea"),
    ("illyria", "kingdom_italy", "land"),
    ("lyonnais", "piedmont", "land"),
    ("galicia_aus", "wallachia", "land"),
    ("galicia_aus", "hungary", "land"),
    ("aquitaine", "ile_de_france", "land"),
    ("ile_de_france", "lyonnais", "land"),
    ("piedmont", "wurttemberg", "land"),
    ("alsace_lorraine", "piedmont", "land"),
    ("kingdom_italy", "wurttemberg", "land"),
    ("bavaria", "kingdom_italy", "land"),
    ("bavaria", "illyria", "land"),
    ("austria_core", "illyria", "land"),
    ("alsace_lorraine", "lyonnais", "land"),
    ("austria_core", "hungary", "land"),
    ("austria_core", "bavaria", "land"),
    ("alsace_lorraine", "wurttemberg", "land"),
    ("ile_de_france", "normandy_brittany", "land"),
    ("bavaria", "wurttemberg", "land"),
    ("galicia_leon", "ireland", "sea"),
    ("moscow", "ukraine", "land"),
    ("ireland", "normandy_brittany", "sea"),
    ("alsace_lorraine", "ile_de_france", "land"),
    ("austria_core", "bohemia", "land"),
    ("alsace_lorraine", "belgium", "land"),
    ("bavaria", "bohemia", "land"),
    ("belgium", "ile_de_france", "land"),
    ("alsace_lorraine", "rhineland", "land"),
    ("rhineland", "wurttemberg", "land"),
    ("bohemia", "hungary", "land"),
    ("bohemia", "saxony", "land"),
    ("bavaria", "saxony", "land"),
    ("hungary", "warsaw", "land"),
    ("galicia_aus", "warsaw", "land"),
    ("ukraine", "west_russia", "land"),
    ("galicia_aus", "west_russia", "land"),
    ("bohemia", "warsaw", "land"),
    ("rhineland", "westphalia", "land"),
    ("england", "normandy_brittany", "sea"),
    ("bavaria", "westphalia", "land"),
    ("england", "ireland", "sea"),
    ("belgium", "rhineland", "land"),
    ("england", "ile_de_france", "land"),
    ("bavaria", "hanover", "land"),
    ("hanover", "westphalia", "land"),
    ("hanover", "saxony", "land"),
    ("galicia_aus", "lithuania", "land"),
    ("lithuania", "west_russia", "land"),
    ("prussia", "saxony", "land"),
    ("bohemia", "prussia", "land"),
    ("belgium", "england", "sea"),
    ("hanover", "prussia", "land"),
    ("belgium", "westphalia", "land"),
    ("east_prussia", "warsaw", "land"),
    ("east_prussia", "lithuania", "land"),
    ("prussia", "warsaw", "land"),
    ("moscow", "west_russia", "land"),
    ("england", "scotland", "sea"),
    ("ireland", "scotland", "sea"),
    ("east_prussia", "prussia", "land"),
    ("denmark", "westphalia", "sea"),
    ("denmark", "hanover", "sea"),
    ("denmark", "prussia", "land"),
    ("belgium", "denmark", "sea"),
    ("prussia", "sweden", "sea"),
    ("east_prussia", "sweden", "sea"),
    ("st_petersburg", "west_russia", "land"),
    ("moscow", "st_petersburg", "land"),
    ("denmark", "sweden", "land"),
    ("lithuania", "st_petersburg", "land"),
    ("denmark", "england", "sea"),
    ("denmark", "scotland", "sea"),
    ("lithuania", "sweden", "land"),
]
CELL_COUNTRIES = {
    "ile_de_france": ["FR", "GB"],
    "normandy_brittany": ["FR", "GB", "JE"],
    "aquitaine": ["ES", "FR"],
    "provence": ["DZ", "FR", "IT"],
    "lyonnais": ["CH", "FR"],
    "alsace_lorraine": ["BE", "CH", "DE", "FR", "LU"],
    "belgium": ["BE", "DE", "FR", "GB", "NL"],
    "castile": ["ES"],
    "catalonia": ["AD", "DZ", "ES", "FR"],
    "andalusia": ["DZ", "ES", "MA"],
    "galicia_leon": ["ES", "PT"],
    "portugal": ["ES", "PT"],
    "piedmont": ["CH", "FR", "IT"],
    "kingdom_italy": ["AT", "CH", "IT"],
    "central_italy": ["FR", "IT"],
    "naples": ["AL", "BA", "HR", "IT", "ME"],
    "sicily": ["DZ", "IT", "MT", "TN"],
    "westphalia": ["DE", "NL"],
    "hanover": ["DE"],
    "rhineland": ["BE", "DE", "FR", "NL"],
    "wurttemberg": ["AT", "CH", "DE", "FR", "LI"],
    "bavaria": ["AT", "CZ", "DE", "IT"],
    "saxony": ["CZ", "DE", "PL"],
    "austria_core": ["AT", "CZ", "HU", "SI", "SK"],
    "bohemia": ["AT", "CZ", "DE", "PL"],
    "hungary": ["BA", "CZ", "HR", "HU", "ME", "PL", "RO", "RS", "SK", "XK"],
    "illyria": ["AT", "BA", "HR", "HU", "IT", "SI"],
    "galicia_aus": ["BY", "HU", "PL", "RO", "SK", "UA"],
    "prussia": ["DE", "DK", "PL", "SE"],
    "east_prussia": ["EE", "LT", "LV", "PL", "RU", "SE"],
    "warsaw": ["PL"],
    "lithuania": ["BY", "EE", "FI", "LT", "LV", "PL", "RU", "UA"],
    "west_russia": ["BY", "RU", "UA"],
    "ukraine": ["MD", "RU", "SY", "TR", "UA"],
    "moscow": ["RU", "UA"],
    "st_petersburg": ["EE", "FI", "RU"],
    "england": ["GB"],
    "scotland": ["GB", "IM"],
    "ireland": ["GB", "IE"],
    "denmark": ["DE", "DK", "NO", "SE"],
    "sweden": ["AX", "FI", "NO", "SE"],
    "rumelia": ["BG", "GR", "MK", "RO", "RS", "SY", "TR", "XK"],
    "greece": ["AL", "GR", "MK", "TR", "XK"],
    "wallachia": ["BG", "MD", "RO", "RS", "UA"],
}

if __name__ == "__main__":
    seeds = {tid: tuple(s) for tid, _n, _r, s in SEEDS}
    cells = voronoi_cells(BOUNDS, seeds)
    territories = []
    admin_refs = {}
    for tid, name, region, _seed in SEEDS:
        ring = cells[tid]
        xs = [p[0] for p in ring]; ys = [p[1] for p in ring]
        cb = [round(min(xs), 2), round(min(ys), 2), round(max(xs), 2), round(max(ys), 2)]
        territories.append((tid, name, region, ring))
        admin_refs[tid] = {
            "geo_config": [{"iso": c, "clip_bbox": cb} for c in CELL_COUNTRIES[tid]],
            "clip_polygon": [ring],
        }
    build_map(
        map_id="community_napoleonic_europe",
        name="Napoleonic Europe — 1812",
        description="Europe at the zenith of Napoleon's power, 1812. Forty-four states from Portugal to Moscow — the French Empire and its satellites against the coalition of Britain, Russia, Prussia, Austria, and the embers of Spain. March on the enemy capital, or hold the line from Lisbon to the Niemen.",
        bounds=BOUNDS,
        regions=REGIONS,
        territories=territories,
        connections=CONNECTIONS,
        globe_view={"center_lat": 49.0, "center_lng": 12.0, "altitude": 1.0},
        era_theme="discovery",
        admin_refs=admin_refs,
    )
