"""
Sengoku Japan — Warring States — generated map. Voronoi tessellation of province seeds, each clipped to its
overlapping modern country geometry for real coastlines and organic, gap-free borders.
Connections are derived from Voronoi adjacency (land/sea typed by the shared border).
Reproducible via mapkit.voronoi_cells; per-cell country lists + connections baked.
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from mapkit import build_map, voronoi_cells

BOUNDS = {"minLng": 129.0, "maxLng": 146.5, "minLat": 30.0, "maxLat": 46.0}
REGIONS = [
    {"region_id": "kyushu", "name": "Kyūshū", "bonus": 4},
    {"region_id": "shikoku", "name": "Shikoku", "bonus": 2},
    {"region_id": "chugoku", "name": "Chūgoku", "bonus": 3},
    {"region_id": "kinki", "name": "Kinki", "bonus": 5},
    {"region_id": "tokai", "name": "Tōkai & Kai", "bonus": 4},
    {"region_id": "hokuriku", "name": "Hokuriku & Shinano", "bonus": 3},
    {"region_id": "kanto", "name": "Kantō", "bonus": 4},
    {"region_id": "tohoku", "name": "Tōhoku & Ezo", "bonus": 3},
]
SEEDS = [
    ("satsuma", "Satsuma (Shimazu)", "kyushu", [130.6, 31.5]),
    ("higo", "Higo", "kyushu", [130.8, 32.6]),
    ("hyuga", "Hyūga", "kyushu", [131.4, 32.2]),
    ("bungo", "Bungo (Ōtomo)", "kyushu", [131.6, 33.2]),
    ("hizen", "Hizen", "kyushu", [130.0, 33.2]),
    ("chikuzen", "Chikuzen & Buzen", "kyushu", [130.6, 33.7]),
    ("tosa", "Tosa (Chōsokabe)", "shikoku", [133.4, 33.4]),
    ("iyo", "Iyo", "shikoku", [132.8, 33.8]),
    ("sanuki_awa", "Sanuki & Awa", "shikoku", [134.2, 34.1]),
    ("nagato", "Nagato (Mōri)", "chugoku", [131.4, 34.3]),
    ("aki", "Aki", "chugoku", [132.6, 34.5]),
    ("izumo", "Izumo", "chugoku", [132.9, 35.3]),
    ("bizen", "Bizen & Mimasaka", "chugoku", [134.0, 34.9]),
    ("harima", "Harima", "kinki", [134.7, 34.9]),
    ("settsu", "Settsu (Ōsaka)", "kinki", [135.4, 34.7]),
    ("yamashiro", "Yamashiro (Kyōto)", "kinki", [135.75, 35.1]),
    ("yamato", "Yamato (Nara)", "kinki", [135.85, 34.4]),
    ("kii", "Kii", "kinki", [135.5, 34.0]),
    ("omi", "Ōmi", "kinki", [136.15, 35.25]),
    ("ise", "Ise", "tokai", [136.5, 34.6]),
    ("owari", "Owari (Oda)", "tokai", [136.9, 35.1]),
    ("mino", "Mino (Saitō)", "tokai", [136.85, 35.6]),
    ("mikawa", "Mikawa (Tokugawa)", "tokai", [137.5, 34.9]),
    ("suruga", "Suruga (Imagawa)", "tokai", [138.4, 35.1]),
    ("kai", "Kai (Takeda)", "tokai", [138.55, 35.6]),
    ("shinano", "Shinano", "hokuriku", [138.0, 36.1]),
    ("echizen", "Echizen", "hokuriku", [136.3, 36.0]),
    ("kaga_etchu", "Kaga & Etchū", "hokuriku", [137.0, 36.7]),
    ("echigo", "Echigo (Uesugi)", "hokuriku", [138.9, 37.5]),
    ("sagami", "Sagami (Hōjō)", "kanto", [139.3, 35.3]),
    ("musashi", "Musashi (Edo)", "kanto", [139.6, 35.9]),
    ("kozuke", "Kōzuke & Shimotsuke", "kanto", [139.4, 36.5]),
    ("hitachi", "Hitachi", "kanto", [140.45, 36.3]),
    ("shimosa", "Shimōsa & Kazusa", "kanto", [140.2, 35.5]),
    ("mutsu_south", "Mutsu (Date)", "tohoku", [140.7, 37.9]),
    ("dewa", "Dewa", "tohoku", [140.0, 39.3]),
    ("mutsu_north", "Northern Mutsu", "tohoku", [141.2, 40.4]),
    ("ezo", "Ezo (Hokkaidō)", "tohoku", [142.8, 43.0]),
]
CONNECTIONS = [
    ("hyuga", "satsuma", "sea"),
    ("hyuga", "tosa", "sea"),
    ("kii", "tosa", "sea"),
    ("kii", "mikawa", "sea"),
    ("mikawa", "suruga", "sea"),
    ("sagami", "suruga", "sea"),
    ("sagami", "shimosa", "sea"),
    ("ise", "kii", "sea"),
    ("ise", "mikawa", "sea"),
    ("hizen", "satsuma", "sea"),
    ("higo", "satsuma", "land"),
    ("higo", "hyuga", "land"),
    ("higo", "hizen", "land"),
    ("bungo", "hyuga", "sea"),
    ("bungo", "tosa", "sea"),
    ("sanuki_awa", "tosa", "land"),
    ("bungo", "higo", "land"),
    ("bungo", "iyo", "sea"),
    ("kii", "sanuki_awa", "sea"),
    ("iyo", "tosa", "land"),
    ("chikuzen", "higo", "land"),
    ("chikuzen", "hizen", "sea"),
    ("bungo", "chikuzen", "land"),
    ("kii", "yamato", "land"),
    ("bungo", "nagato", "sea"),
    ("ise", "yamato", "land"),
    ("chikuzen", "nagato", "sea"),
    ("aki", "iyo", "sea"),
    ("hitachi", "shimosa", "sea"),
    ("aki", "nagato", "land"),
    ("iyo", "sanuki_awa", "sea"),
    ("harima", "sanuki_awa", "sea"),
    ("kii", "settsu", "land"),
    ("bizen", "sanuki_awa", "sea"),
    ("harima", "settsu", "land"),
    ("aki", "bizen", "land"),
    ("settsu", "yamato", "land"),
    ("bizen", "harima", "sea"),
    ("ise", "owari", "sea"),
    ("aki", "izumo", "land"),
    ("yamashiro", "yamato", "land"),
    ("mikawa", "owari", "land"),
    ("bizen", "izumo", "sea"),
    ("settsu", "yamashiro", "land"),
    ("ise", "omi", "land"),
    ("omi", "yamashiro", "land"),
    ("omi", "owari", "land"),
    ("izumo", "nagato", "sea"),
    ("harima", "yamashiro", "land"),
    ("mino", "owari", "land"),
    ("kai", "suruga", "land"),
    ("kai", "sagami", "land"),
    ("mino", "omi", "land"),
    ("mikawa", "mino", "land"),
    ("shinano", "suruga", "land"),
    ("musashi", "sagami", "land"),
    ("mikawa", "shinano", "land"),
    ("musashi", "shimosa", "land"),
    ("echizen", "omi", "land"),
    ("kai", "shinano", "land"),
    ("echizen", "mino", "land"),
    ("mino", "shinano", "land"),
    ("echizen", "yamashiro", "sea"),
    ("kai", "musashi", "land"),
    ("kozuke", "musashi", "land"),
    ("hitachi", "musashi", "land"),
    ("kaga_etchu", "mino", "land"),
    ("kai", "kozuke", "land"),
    ("echizen", "harima", "sea"),
    ("kaga_etchu", "shinano", "land"),
    ("hitachi", "mutsu_south", "sea"),
    ("echizen", "kaga_etchu", "sea"),
    ("kozuke", "shinano", "land"),
    ("hitachi", "kozuke", "land"),
    ("echigo", "shinano", "land"),
    ("echigo", "kozuke", "land"),
    ("bizen", "echizen", "sea"),
    ("echigo", "kaga_etchu", "sea"),
    ("kozuke", "mutsu_south", "land"),
    ("echizen", "izumo", "sea"),
    ("echigo", "mutsu_south", "land"),
    ("mutsu_north", "mutsu_south", "sea"),
    ("dewa", "echigo", "sea"),
    ("dewa", "mutsu_south", "land"),
    ("ezo", "mutsu_north", "sea"),
    ("izumo", "kaga_etchu", "sea"),
    ("dewa", "mutsu_north", "sea"),
    ("dewa", "kaga_etchu", "land"),
]
CELL_COUNTRIES = {
    "satsuma": ["JP"],
    "higo": ["JP"],
    "hyuga": ["JP"],
    "bungo": ["JP"],
    "hizen": ["JP"],
    "chikuzen": ["JP"],
    "tosa": ["JP"],
    "iyo": ["JP"],
    "sanuki_awa": ["JP"],
    "nagato": ["JP"],
    "aki": ["JP"],
    "izumo": ["JP"],
    "bizen": ["JP"],
    "harima": ["JP"],
    "settsu": ["JP"],
    "yamashiro": ["JP"],
    "yamato": ["JP"],
    "kii": ["JP"],
    "omi": ["JP"],
    "ise": ["JP"],
    "owari": ["JP"],
    "mino": ["JP"],
    "mikawa": ["JP"],
    "suruga": ["JP"],
    "kai": ["JP"],
    "shinano": ["JP"],
    "echizen": ["JP"],
    "kaga_etchu": ["JP"],
    "echigo": ["JP"],
    "sagami": ["JP"],
    "musashi": ["JP"],
    "kozuke": ["JP"],
    "hitachi": ["JP"],
    "shimosa": ["JP"],
    "mutsu_south": ["JP"],
    "dewa": ["JP"],
    "mutsu_north": ["JP"],
    "ezo": ["JP"],
}

if __name__ == "__main__":
    seeds = {tid: tuple(s) for tid, _n, _r, s in SEEDS}
    cells = voronoi_cells(BOUNDS, seeds)
    territories = []
    admin_refs = {}
    for tid, name, region, _seed in SEEDS:
        ring = cells[tid]
        xs = [p[0] for p in ring]; ys = [p[1] for p in ring]
        cb = [round(min(xs), 2), round(min(ys), 2), round(max(xs), 2), round(max(ys), 2)]
        territories.append((tid, name, region, ring))
        admin_refs[tid] = {
            "geo_config": [{"iso": c, "clip_bbox": cb} for c in CELL_COUNTRIES[tid]],
            "clip_polygon": [ring],
        }
    build_map(
        map_id="community_sengoku_japan",
        name="Sengoku Japan — Warring States",
        description="Japan in the age of the warring states. Thirty-eight provinces from Satsuma to Ezo contest the realm as the great clans — Shimazu, Mōri, Oda, Takeda, Uesugi, Hōjō, Date, Tokugawa — fight to march on Kyōto and unify the country. Mountain passes and the Inland Sea draw every front.",
        bounds=BOUNDS,
        regions=REGIONS,
        territories=territories,
        connections=CONNECTIONS,
        globe_view={"center_lat": 36.0, "center_lng": 138.0, "altitude": 0.55},
        era_theme="medieval",
        admin_refs=admin_refs,
    )
