"""
Mongol Empire — 1279 — generated map. Voronoi tessellation of province seeds, each clipped to its
overlapping modern country geometry for real coastlines and organic, gap-free borders.
Connections are derived from Voronoi adjacency (land/sea typed by the shared border).
Reproducible via mapkit.voronoi_cells; per-cell country lists + connections baked.
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from mapkit import build_map, voronoi_cells

BOUNDS = {"minLng": 24.0, "maxLng": 135.0, "minLat": 17.0, "maxLat": 58.0}
REGIONS = [
    {"region_id": "yuan", "name": "Yuan China", "bonus": 6},
    {"region_id": "steppe_core", "name": "The Mongol Heartland", "bonus": 4},
    {"region_id": "chagatai", "name": "Chagatai Khanate", "bonus": 4},
    {"region_id": "ilkhanate", "name": "Ilkhanate", "bonus": 5},
    {"region_id": "golden_horde", "name": "Golden Horde", "bonus": 5},
    {"region_id": "eastern", "name": "Korea & Manchuria", "bonus": 3},
    {"region_id": "tibet_yun", "name": "Tibet & Yunnan", "bonus": 3},
]
SEEDS = [
    ("zhongshu", "Dadu & Zhongshu", "yuan", [116.5, 40.0]),
    ("shandong", "Shandong", "yuan", [118.2, 36.3]),
    ("shaanxi", "Shaanxi & Gansu", "yuan", [107.0, 35.0]),
    ("sichuan", "Sichuan", "yuan", [104.0, 30.5]),
    ("jiangzhe", "Jiangzhe", "yuan", [119.5, 30.8]),
    ("huguang", "Huguang", "yuan", [112.0, 28.0]),
    ("jiangxi", "Jiangxi & Lingnan", "yuan", [114.5, 25.0]),
    ("henan", "Henan & Jiangbei", "yuan", [114.0, 33.5]),
    ("manchuria", "Liaoyang (Manchuria)", "eastern", [125.0, 45.0]),
    ("korea", "Goryeo (Korea)", "eastern", [127.5, 37.0]),
    ("amur", "Outer Manchuria", "eastern", [130.0, 50.0]),
    ("mongolia_east", "Karakorum", "steppe_core", [108.0, 47.5]),
    ("mongolia_west", "Altai", "steppe_core", [92.0, 47.0]),
    ("siberia", "Southern Siberia", "steppe_core", [85.0, 54.0]),
    ("tibet", "Tibet", "tibet_yun", [89.0, 31.5]),
    ("yunnan", "Yunnan", "tibet_yun", [101.5, 25.0]),
    ("tarim", "Tarim Basin", "chagatai", [81.0, 39.5]),
    ("dzungaria", "Dzungaria", "chagatai", [84.0, 45.0]),
    ("transoxiana", "Transoxiana", "chagatai", [66.0, 40.0]),
    ("khwarazm", "Khwarazm", "chagatai", [60.0, 43.5]),
    ("kazakh_steppe", "Kazakh Steppe", "chagatai", [68.0, 48.0]),
    ("khorasan", "Khorasan", "ilkhanate", [58.0, 35.5]),
    ("persia_central", "Jibal & Isfahan", "ilkhanate", [52.0, 33.0]),
    ("fars", "Fars", "ilkhanate", [53.5, 28.5]),
    ("azerbaijan", "Azerbaijan", "ilkhanate", [47.5, 38.0]),
    ("mesopotamia", "Baghdad (Iraq)", "ilkhanate", [44.0, 33.0]),
    ("anatolia", "Rum (Anatolia)", "ilkhanate", [35.0, 39.0]),
    ("caucasus", "Caucasus", "ilkhanate", [44.5, 42.0]),
    ("lower_volga", "Sarai (Lower Volga)", "golden_horde", [47.0, 47.5]),
    ("ural", "Ural & Sibir", "golden_horde", [60.0, 53.0]),
    ("pontic", "Pontic Steppe", "golden_horde", [36.0, 47.5]),
    ("crimea", "Crimea", "golden_horde", [34.5, 45.2]),
    ("volga_bulgaria", "Volga Bulgaria", "golden_horde", [49.5, 55.0]),
    ("rus_kiev", "Rus' (Kiev)", "golden_horde", [31.0, 50.5]),
    ("rus_vladimir", "Rus' (Vladimir)", "golden_horde", [39.0, 56.0]),
    ("rus_novgorod", "Novgorod", "golden_horde", [32.0, 58.0]),
]
CONNECTIONS = [
    ("anatolia", "mesopotamia", "land"),
    ("fars", "mesopotamia", "land"),
    ("fars", "tibet", "sea"),
    ("tibet", "yunnan", "land"),
    ("jiangxi", "yunnan", "sea"),
    ("jiangxi", "jiangzhe", "sea"),
    ("jiangzhe", "korea", "sea"),
    ("fars", "transoxiana", "land"),
    ("tibet", "transoxiana", "land"),
    ("huguang", "jiangxi", "land"),
    ("huguang", "yunnan", "land"),
    ("fars", "khorasan", "land"),
    ("khorasan", "transoxiana", "land"),
    ("tarim", "tibet", "land"),
    ("tarim", "transoxiana", "land"),
    ("sichuan", "yunnan", "land"),
    ("huguang", "sichuan", "land"),
    ("huguang", "jiangzhe", "land"),
    ("fars", "persia_central", "land"),
    ("mesopotamia", "persia_central", "land"),
    ("henan", "huguang", "land"),
    ("henan", "jiangzhe", "land"),
    ("sichuan", "tibet", "land"),
    ("shaanxi", "sichuan", "land"),
    ("huguang", "shaanxi", "land"),
    ("khorasan", "persia_central", "land"),
    ("henan", "shaanxi", "land"),
    ("jiangzhe", "shandong", "land"),
    ("henan", "shandong", "land"),
    ("azerbaijan", "persia_central", "land"),
    ("azerbaijan", "mesopotamia", "land"),
    ("korea", "shandong", "sea"),
    ("henan", "zhongshu", "land"),
    ("shandong", "zhongshu", "land"),
    ("caucasus", "mesopotamia", "land"),
    ("azerbaijan", "caucasus", "land"),
    ("anatolia", "caucasus", "land"),
    ("mongolia_west", "tibet", "land"),
    ("mongolia_west", "shaanxi", "land"),
    ("shaanxi", "zhongshu", "land"),
    ("azerbaijan", "khorasan", "land"),
    ("khorasan", "khwarazm", "land"),
    ("khwarazm", "transoxiana", "land"),
    ("dzungaria", "tarim", "land"),
    ("dzungaria", "tibet", "land"),
    ("dzungaria", "mongolia_west", "land"),
    ("korea", "manchuria", "land"),
    ("manchuria", "zhongshu", "land"),
    ("azerbaijan", "khwarazm", "land"),
    ("mongolia_east", "shaanxi", "land"),
    ("anatolia", "crimea", "sea"),
    ("mongolia_east", "zhongshu", "land"),
    ("mongolia_east", "mongolia_west", "land"),
    ("crimea", "rus_kiev", "land"),
    ("kazakh_steppe", "transoxiana", "land"),
    ("kazakh_steppe", "tarim", "land"),
    ("amur", "korea", "sea"),
    ("caucasus", "crimea", "sea"),
    ("azerbaijan", "lower_volga", "sea"),
    ("caucasus", "lower_volga", "land"),
    ("amur", "manchuria", "land"),
    ("khwarazm", "lower_volga", "land"),
    ("crimea", "pontic", "land"),
    ("caucasus", "pontic", "land"),
    ("kazakh_steppe", "khwarazm", "land"),
    ("dzungaria", "kazakh_steppe", "land"),
    ("lower_volga", "pontic", "land"),
    ("pontic", "rus_kiev", "land"),
    ("khwarazm", "ural", "land"),
    ("lower_volga", "ural", "land"),
    ("kazakh_steppe", "ural", "land"),
    ("dzungaria", "siberia", "land"),
    ("manchuria", "mongolia_east", "land"),
    ("lower_volga", "volga_bulgaria", "land"),
    ("mongolia_west", "siberia", "land"),
    ("ural", "volga_bulgaria", "land"),
    ("pontic", "rus_vladimir", "land"),
    ("lower_volga", "rus_vladimir", "land"),
    ("kazakh_steppe", "siberia", "land"),
    ("rus_kiev", "rus_vladimir", "land"),
    ("rus_vladimir", "volga_bulgaria", "land"),
    ("rus_kiev", "rus_novgorod", "land"),
    ("rus_novgorod", "rus_vladimir", "land"),
    ("amur", "mongolia_east", "land"),
]
CELL_COUNTRIES = {
    "zhongshu": ["CN", "MN"],
    "shandong": ["CN"],
    "shaanxi": ["CN"],
    "sichuan": ["CN"],
    "jiangzhe": ["CN", "CN-TW"],
    "huguang": ["CN"],
    "jiangxi": ["CN", "CN-TW", "HK", "PH"],
    "henan": ["CN"],
    "manchuria": ["CN", "KP", "MN", "RU"],
    "korea": ["CN", "JP", "KP", "KR"],
    "amur": ["CN", "RU"],
    "mongolia_east": ["CN", "MN", "RU"],
    "mongolia_west": ["CN", "MN", "RU"],
    "siberia": ["KZ", "RU"],
    "tibet": ["BD", "BT", "CN", "IN", "NP"],
    "yunnan": ["BD", "CN", "IN", "LA", "MM", "TH", "VN"],
    "tarim": ["AF", "CN", "IN", "KG", "KZ", "PK", "TJ"],
    "dzungaria": ["CN", "KZ"],
    "transoxiana": ["AF", "IN", "KG", "KZ", "PK", "TJ", "TM", "UZ"],
    "khwarazm": ["KZ", "TM", "UZ"],
    "kazakh_steppe": ["KG", "KZ", "RU"],
    "khorasan": ["AF", "IN", "IR", "PK", "TM"],
    "persia_central": ["IQ", "IR", "KW"],
    "fars": ["AE", "IN", "IR", "KW", "OM", "PK", "QA", "SA", "YE"],
    "azerbaijan": ["AM", "AZ", "IQ", "IR", "KZ", "RU", "TM", "TR"],
    "mesopotamia": ["EG", "ER", "IQ", "IR", "JO", "KW", "SA", "SD", "SY", "TR"],
    "anatolia": ["BG", "CY", "EG", "GR", "IL", "JO", "LB", "LY", "PS", "SD", "SY", "TR"],
    "caucasus": ["AM", "AZ", "GE", "IR", "RU", "TR"],
    "lower_volga": ["KZ", "RU"],
    "ural": ["KZ", "RU"],
    "pontic": ["RU", "UA"],
    "crimea": ["BG", "GR", "RO", "RU", "TR", "UA"],
    "volga_bulgaria": ["KZ", "RU"],
    "rus_kiev": ["BG", "BY", "LT", "MD", "RO", "RU", "UA"],
    "rus_vladimir": ["RU"],
    "rus_novgorod": ["BY", "EE", "LT", "LV", "RU"],
}

if __name__ == "__main__":
    seeds = {tid: tuple(s) for tid, _n, _r, s in SEEDS}
    cells = voronoi_cells(BOUNDS, seeds)
    territories = []
    admin_refs = {}
    for tid, name, region, _seed in SEEDS:
        ring = cells[tid]
        xs = [p[0] for p in ring]; ys = [p[1] for p in ring]
        cb = [round(min(xs), 2), round(min(ys), 2), round(max(xs), 2), round(max(ys), 2)]
        territories.append((tid, name, region, ring))
        admin_refs[tid] = {
            "geo_config": [{"iso": c, "clip_bbox": cb} for c in CELL_COUNTRIES[tid]],
            "clip_polygon": [ring],
        }
    build_map(
        map_id="community_mongol_empire",
        name="Mongol Empire — 1279",
        description="The Mongol Empire at its height, 1279, the year Kublai Khan completed the conquest of Song China. Thirty-six provinces across the largest contiguous land empire in history — Yuan China, the Mongol heartland, the Chagatai khanate, the Ilkhanate of Persia, and the Golden Horde over the Rus' and the steppe. Reunite the ulus or break it apart.",
        bounds=BOUNDS,
        regions=REGIONS,
        territories=territories,
        connections=CONNECTIONS,
        globe_view={"center_lat": 42.0, "center_lng": 80.0, "altitude": 1.6},
        era_theme="medieval",
        admin_refs=admin_refs,
    )
