import type { Faction, TechNode, EraWonder } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
// Space Age (circa 2100 AD): post-nation megastates, corporate enclaves, and
// the first permanent lunar settlement jostling for planetary — and orbital — dominance.
export const SPACE_AGE_FACTIONS: Faction[] = [
  {
    faction_id: 'terran_federation',
    name: 'Terran Federation',
    description: 'Satellite-backed democracies — +1 attack die from surveillance dominance; precision doctrine always active.',
    lore: 'A confederation of North Atlantic and European megastates bound together by shared orbital infrastructure and open data networks.',
    flavor_quote: 'Transparency is the sharpest weapon of the free.',
    home_region_ids: ['north_america_2100', 'europe_2100'],
    passive_attack_bonus: 1,
    passive_defense_bonus: 1,
    ability_id: 'orbital_surveillance',
    ability_description: 'Orbital Surveillance: once per turn, reveal all units in an adjacent enemy territory and gain +1 attack die against it this turn.',
    color: '#3498db',
    stability_recovery_bonus: 2,
  },
  {
    faction_id: 'sino_hegemony',
    name: 'Sino-Pacific Hegemony',
    description: 'Automated industry + AI command — +2 reinforcements per turn; additional production from every tech_gen building.',
    lore: 'A tightly integrated Asia-Pacific bloc where AI planners schedule factory output, logistics, and troop rotations with ruthless efficiency.',
    flavor_quote: 'The machine does not sleep; neither does the empire.',
    home_region_ids: ['asia_2100'],
    reinforce_bonus: 2,
    ability_id: 'ai_surge',
    ability_description: 'AI Surge: once per turn, spend 5 tech points to place 3 units on any owned territory.',
    color: '#c0392b',
  },
  {
    faction_id: 'climate_alliance',
    name: 'Climate Alliance',
    description: 'Terraforming doctrine — +2 stability recovery per turn; territories recover population faster.',
    lore: 'Born from the flooded coastlines and dust belts of the late 21st century, the Alliance treats ecological repair as a strategic weapon.',
    flavor_quote: 'We build the future in soil, not steel.',
    home_region_ids: ['sub_saharan_africa_2100', 'oceania_2100'],
    passive_defense_bonus: 1,
    ability_id: 'terraform',
    ability_description: 'Terraform: once per turn, restore stability to 100 in an owned territory and gain 1 free unit there.',
    color: '#16a085',
    stability_recovery_bonus: 4,
  },
  {
    faction_id: 'corpo_enclave',
    name: 'Corporate Enclave',
    description: 'Private militaries and techno-capitalism — +4 tech points per turn; can purchase mercenaries.',
    lore: 'Post-state megacorporations ruling sovereign coastal cities, blurring the boundary between shareholders and citizens.',
    flavor_quote: 'Loyalty is a line item, not a virtue.',
    home_region_ids: ['coastal_megacities_2100', 'latin_america_2100'],
    ability_id: 'mercenary_contract',
    ability_description: 'Mercenary Contract: once per turn, spend 6 tech points to place 4 units on any territory you own that has a production building.',
    color: '#9b59b6',
  },
  {
    faction_id: 'solar_caliphate',
    name: 'Solar Caliphate',
    description: 'Vast solar arrays + hydrogen economy — +3 tech points per turn; extra reinforcement for every 3 owned resource territories.',
    lore: 'A post-petroleum coalition of Gulf and Central Asian states that turned their deserts into the energy heart of the 22nd century.',
    flavor_quote: 'The sun no longer rises in the East; it is owned there.',
    home_region_ids: ['middle_east_2100', 'central_asia_2100'],
    reinforce_bonus: 1,
    ability_id: 'power_projection',
    ability_description: 'Power Projection: once per turn, pay 4 tech points to attack any territory within 2 hops.',
    color: '#f39c12',
  },
  {
    faction_id: 'lunar_pioneers',
    name: 'Lunar Pioneers',
    description: 'Moon-native colonists — start with Moon access unlocked; +2 defense dice on all lunar territories.',
    lore: 'Descendants of the first permanent lunar settlers, the Pioneers see Earth as a gravity well they are no longer obligated to return to.',
    flavor_quote: 'We do not look up at the stars. We live among them.',
    home_region_ids: ['lunar_surface'],
    passive_defense_bonus: 2,
    ability_id: 'lunar_supply_drop',
    ability_description: 'Lunar Supply Drop: once per turn, drop 2 units into any owned Moon territory.',
    color: '#bdc3c7',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
// 13 nodes across 4 tiers. The "Space Program" branch (orbital_recon →
// launch_pad_tech → space_station → lunar_expansion) is the Moon-gating path.
export const SPACE_AGE_TECH_TREE: TechNode[] = [
  // ── Tier 1 ───────────────────────────────────────────────────────────────
  {
    tech_id: 'sa_digital_warfare',
    name: 'Digital Warfare',
    description: 'Cyber-enabled command — +1 attack die; unlocks data_breach ability.',
    tier: 1,
    cost: 5,
    attack_bonus: 1,
    unlocks_ability: 'data_breach',
  },
  {
    tech_id: 'sa_megacity',
    name: 'Megacity Logistics',
    description: 'Vertical cities and automated supply chains — unlocks production_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'sa_climate_shield',
    name: 'Climate Shielding',
    description: 'Weather-proof bunkers — +1 defense die; unlocks defense_1 building.',
    tier: 1,
    cost: 4,
    defense_bonus: 1,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'sa_orbital_recon',
    name: 'Orbital Reconnaissance',
    description: 'Low-Earth-orbit satellite constellation — reveal adjacent enemy territories each turn.',
    tier: 1,
    prerequisite: 'sa_digital_warfare',
    cost: 6,
    unlocks_ability: 'orbital_recon',
  },

  // ── Tier 2 ───────────────────────────────────────────────────────────────
  {
    tech_id: 'sa_ai_command',
    name: 'AI-Directed Command',
    description: 'Autonomous battlefield AI — +1 attack die; +2 tech points per turn.',
    tier: 2,
    prerequisite: 'sa_digital_warfare',
    cost: 9,
    attack_bonus: 1,
    tech_point_income: 2,
  },
  {
    tech_id: 'sa_fusion_power',
    name: 'Fusion Power Grid',
    description: 'Abundant energy — unlocks tech_gen_1 building and +3 tech points per turn.',
    tier: 2,
    prerequisite: 'sa_megacity',
    cost: 9,
    tech_point_income: 3,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'sa_launch_pad_tech',
    name: 'Spaceport Infrastructure',
    description: 'Heavy-lift launch facilities — unlocks Launch Pad building in any owned territory (required to reach the Moon).',
    tier: 2,
    prerequisite: 'sa_orbital_recon',
    cost: 12,
    unlocks_building: 'launch_pad',
  },

  // ── Tier 3 ───────────────────────────────────────────────────────────────
  {
    tech_id: 'sa_hypersonic_swarm',
    name: 'Hypersonic Swarm',
    description: 'Networked hypersonic drones — +2 attack dice; once per turn, unleash a swarm strike on an adjacent enemy.',
    tier: 3,
    prerequisite: 'sa_ai_command',
    cost: 14,
    attack_bonus: 2,
    unlocks_ability: 'swarm_strike',
  },
  {
    tech_id: 'sa_quantum_grid',
    name: 'Quantum Computing Grid',
    description: 'Post-classical computation — unlocks tech_gen_2 building and +5 tech points per turn.',
    tier: 3,
    prerequisite: 'sa_fusion_power',
    cost: 14,
    tech_point_income: 5,
    unlocks_building: 'tech_gen_2',
  },
  {
    tech_id: 'sa_space_station',
    name: 'Orbital Station Program',
    description: 'Modular assembly in low Earth orbit — unlocks the Launch Space Station ability (required to reach the Moon).',
    tier: 3,
    prerequisite: 'sa_launch_pad_tech',
    cost: 18,
    unlocks_ability: 'launch_space_station',
  },

  // ── Tier 4 ───────────────────────────────────────────────────────────────
  {
    tech_id: 'sa_singularity_war',
    name: 'Singularity Warfare',
    description: 'Self-improving military AI — +2 attack, +1 defense, +3 reinforcements per turn.',
    tier: 4,
    prerequisite: 'sa_hypersonic_swarm',
    cost: 24,
    attack_bonus: 2,
    defense_bonus: 1,
    reinforce_bonus: 3,
  },
  {
    tech_id: 'sa_dyson_array',
    name: 'Dyson Array Prototype',
    description: 'Solar-harvesting megastructure — +8 tech points per turn; unlocks dyson_beam planetary strike.',
    tier: 4,
    prerequisite: 'sa_quantum_grid',
    cost: 26,
    tech_point_income: 8,
    unlocks_ability: 'dyson_beam',
  },
  {
    tech_id: 'sa_lunar_expansion',
    name: 'Lunar Expansion',
    description: 'Crewed lunar missions and permanent bases — grants access to Moon territories via orbital connections.',
    tier: 4,
    prerequisite: 'sa_space_station',
    cost: 22,
  },
];

// ── Wonder ────────────────────────────────────────────────────────────────────
export const SPACE_AGE_WONDER: EraWonder = {
  wonder_id: 'wonder_space_elevator',
  name: 'Space Elevator',
  description: 'Tethered orbital ribbon — Moon access requires only Lunar Expansion tech + Launch Pad (skips Space Station launch).',
  cost: 28,
  passive_effect_type: 'influence_range',
  passive_effect_value: 1,
};
